In [321]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.patches import Patch
from matplotlib.lines import Line2D
import seaborn as sns
from termcolor import colored

df = pd.read_json("scout_car.json", lines=True)
df

,url,make_model,short_description,body_type,price,vat,km,registration,prev_owner,kW,...,description,Emission Label,Gears,Country version,Electricity consumption,Last Service Date,Other Fuel Types,Availability,Last Timing Belt Service Date,Available from
0,https://www.autoscout24.com//offers/audi-a1-sp...,Audi A1,Sportback 1.4 TDI S-tronic Xenon Navi Klima,Sedans,15770,VAT deductible,"56,013 km",01/2016,2 previous owners,NaN,...,"[\n, Sicherheit:, , Deaktivierung f√ºr Beifahr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.autoscout24.com//offers/audi-a1-1-...,Audi A1,1.8 TFSI sport,Sedans,14500,Price negotiable,"80,000 km",03/2017,None,NaN,...,[\nLangstreckenfahrzeug daher die hohe Kilomet...,[\n4 (Green)\n],[\n7\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.autoscout24.com//offers/audi-a1-sp...,Audi A1,Sportback 1.6 TDI S tronic Einparkhilfe plus+m...,Sedans,14640,VAT deductible,"83,450 km",02/2016,1 previous owner,NaN,...,"[\n, Fahrzeug-Nummer: AM-95365, , Ehem. UPE 2...",[\n4 (Green)\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.autoscout24.com//offers/audi-a1-1-...,Audi A1,1.4 TDi Design S tronic,Sedans,14500,None,"73,000 km",08/2016,1 previous owner,NaN,...,"[\nAudi A1: , - 1e eigenaar , - Perfecte staat...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.autoscout24.com//offers/audi-a1-sp...,Audi A1,Sportback 1.4 TDI S-Tronic S-Line Ext. admired...,Sedans,16790,None,"16,200 km",05/2016,1 previous owner,NaN,...,"[\n, Technik & Sicherheit:, Xenon plus, Klimaa...",NaN,NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15914,https://www.autoscout24.com//offers/renault-es...,Renault Espace,Blue dCi 200CV EDC Executive 4Control,Van,39950,VAT deductible,- km,-/-,None,NaN,...,[\nVettura visionabile nella sede in Via Roma ...,NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
15915,https://www.autoscout24.com//offers/renault-es...,Renault Espace,"TCe 225 EDC GPF LIM Deluxe Pano,RFK",Van,39885,VAT deductible,"9,900 km",01/2019,1 previous owner,NaN,...,"[\nDach: Panorama-Glas-Schiebedach, Lackierung...",NaN,[\n7\n],[\nGermany\n],NaN,NaN,"[[], [], []]",\nin 5 days from ordering\n,NaN,NaN
15916,https://www.autoscout24.com//offers/renault-es...,Renault Espace,Blue dCi 200 EDC Initiale Paris Leder LED Navi...,Van,39875,VAT deductible,15 km,03/2019,1 previous owner,NaN,...,"[\n, Getriebe:, Automatik, Technik:, Bordcom...",NaN,[\n6\n],[\nAustria\n],NaN,NaN,NaN,\nin 120 days from ordering\n,NaN,NaN
15917,https://www.autoscout24.com//offers/renault-es...,Renault Espace,"Blue dCi 200CV EDC Business , NUOVA DA IMMATRI...",Van,39700,VAT deductible,10 km,06/2019,None,NaN,...,"[\nDEK:[2691331], Renault Espace Blue dCi 200C...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
15918,https://www.autoscout24.com//offers/renault-es...,Renault Espace,INITIALE PARIS TCe 225 EDC GPF NAVI SHZ AUX,Van,40999,VAT deductible,- km,01/2019,1 previous owner,NaN,...,"[\n, Sicherheit Airbags:, , Seitenairbag, , ...",[\n4 (Green)\n],NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN

In [322]:
df.head().T

,0,1,2,3,4
url,https://www.autoscout24.com//offers/audi-a1-sp...,https://www.autoscout24.com//offers/audi-a1-1-...,https://www.autoscout24.com//offers/audi-a1-sp...,https://www.autoscout24.com//offers/audi-a1-1-...,https://www.autoscout24.com//offers/audi-a1-sp...
make_model,Audi A1,Audi A1,Audi A1,Audi A1,Audi A1
short_description,Sportback 1.4 TDI S-tronic Xenon Navi Klima,1.8 TFSI sport,Sportback 1.6 TDI S tronic Einparkhilfe plus+m...,1.4 TDi Design S tronic,Sportback 1.4 TDI S-Tronic S-Line Ext. admired...
body_type,Sedans,Sedans,Sedans,Sedans,Sedans
price,15770,14500,14640,14500,16790
vat,VAT deductible,Price negotiable,VAT deductible,None,None
km,"56,013 km","80,000 km","83,450 km","73,000 km","16,200 km"
registration,01/2016,03/2017,02/2016,08/2016,05/2016
prev_owner,2 previous owners,None,1 previous owner,1 previous owner,1 previous owner
kW,NaN,NaN,NaN,NaN,NaN
hp,66 kW,141 kW,85 kW,66 kW,66 kW
Type,"[, Used, , Diesel (Particulate Filter)]","[, Used, , Gasoline]","[, Used, , Diesel (Particulate Filter)]","[, Used, , Diesel (Particulate Filter)]","[, Used, , Diesel (Particulate Filter)]"
Previous Owners,\n2\n,NaN,\n1\n,\n1\n,\n1\n
Next Inspection,"[\n06/2021\n, \n99 g CO2/km (comb)\n]",NaN,NaN,NaN,NaN
Inspection new,"[\nYes\n, \nEuro 6\n]",NaN,NaN,NaN,"[\nYes\n, \n109 g CO2/km (comb)\n]"
Warranty,"[\n, \n, \n4 (Green)\n]",NaN,"[\n, \n, \n99 g CO2/km (comb)\n]",NaN,"[\n, \n, \nEuro 6\n]"
Full Service,"[\n, \n]",NaN,NaN,"[\n, \n, \n99 g CO2/km (comb)\n]","[\n, \n, \n4 (Green)\n]"
Non-smoking Vehicle,"[\n, \n]",NaN,NaN,"[\n, \n, \nEuro 6\n]","[\n, \n]"
null,[],[],[],[],[]
Make,\nAudi\n,\nAudi\n,\nAudi\n,\nAudi\n,\nAudi\n
Model,"[\n, A1, \n]","[\n, A1, \n]","[\n, A1, \n]","[\n, A1, \n]","[\n, A1, \n]"
Offer Number,[\nLR-062483\n],NaN,[\nAM-95365\n],NaN,[\nC1626\n]
First Registration,"[\n, 2016, \n]","[\n, 2017, \n]","[\n, 2016, \n]","[\n, 2016, \n]","[\n, 2016, \n]"
Body Color,"[\n, Black, \n]","[\n, Red, \n]","[\n, Black, \n]","[\n, Brown, \n]","[\n, Black, \n]"
Paint Type,[\nMetallic\n],NaN,[\nMetallic\n],[\nMetallic\n],[\nMetallic\n]
Body Color Original,[\nMythosschwarz\n],NaN,[\nmythosschwarz metallic\n],NaN,[\nMythosschwarz Metallic\n]
Upholstery,"[\nCloth, Black\n]","[\nCloth, Grey\n]","[\nCloth, Black\n]",NaN,"[\nCloth, Black\n]"
Body,"[\n, Sedans, \n]","[\n, Sedans, \n]","[\n, Sedans, \n]","[\n, Sedans, \n]","[\n, Sedans, \n]"
Nr. of Doors,[\n5\n],[\n3\n],[\n4\n],[\n3\n],[\n5\n]
Nr. of Seats,[\n5\n],[\n4\n],[\n4\n],[\n4\n],[\n5\n]
Model Code,[\n0588/BDF\n],[\n0588/BCY\n],NaN,NaN,[\n0588/BDF\n]
Gearing Type,"[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]"
Displacement,"[\n1,422 cc\n]","[\n1,798 cc\n]","[\n1,598 cc\n]","[\n1,422 cc\n]","[\n1,422 cc\n]"
Cylinders,[\n3\n],[\n4\n],NaN,[\n3\n],[\n3\n]
Weight,"[\n1,220 kg\n]","[\n1,255 kg\n]",NaN,"[\n1,195 kg\n]",NaN
Drive chain,[\nfront\n],[\nfront\n],[\nfront\n],NaN,[\nfront\n]
Fuel,"[\n, Diesel (Particulate Filter), \n]","[\n, Gasoline, \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Diesel (Particulate Filter), \n]"
Consumption,"[[3.8 l/100 km (comb)], [4.3 l/100 km (city)],...","[[5.6 l/100 km (comb)], [7.1 l/100 km (city)],...","[[3.8 l/100 km (comb)], [4.4 l/100 km (city)],...","[[3.8 l/100 km (comb)], [4.3 l/100 km (city)],...","[[4.1 l/100 km (comb)], [4.6 l/100 km (city)],..."
CO2 Emission,[\n99 g CO2/km (comb)\n],[\n129 g CO2/km (comb)\n],[\n99 g CO2/km (comb)\n],[\n99 g CO2/km (comb)\n],[\n109 g CO2/km (comb)\n]
Emission Class,[\nEuro 6\n],[\nEuro 6\n],[\nEuro 6\n],[\nEuro 6\n],[\nEuro 6\n]
\nComfort & Convenience\n,"[Air conditioning, Armrest, Automatic climate ...","[Air conditioning, Automatic climate control, ...","[Air conditioning, Cruise control, Electrical ...","[Air suspension, Armrest, Auxiliary heating, E...","[Air conditioning, Armrest, Automatic climate ..."
\nEntertainment & Media\n,"[Bluetooth, Hands-free equipment, On-board com...","[Bluetooth, Hands-free equipment, On-board com...","[MP3, On-board computer]","[Bluetooth, CD player, Hands-free equipment, M...","[Bluetooth, CD player, Hands-free equipment, M..."
\nExtras\n,"[Alloy wheels, Catalytic Converter, Voice Cont...","[Alloy wheels, Sport seats, Sport suspension, ...","[Alloy wheels, Voice Control]","[Alloy wheels, Sport seats, Voice Control]","[Alloy wheels, Sport package, Sport suspension..."
\nSafety & Security\n,"[ABS, Central door lock, Daytime running light...","[ABS, Central door lock, Central door lock wit...","[ABS, Central door lock, Daytime running light...","[ABS, Alarm system, Central door lock with rem...","[ABS, Central door lock, Driver-side airbag, E..."
description,"[\n, Sicherheit:, , Deaktivierung f√ºr Beifahr...",[\nLangstreckenfahrzeug daher die hohe Kilomet...,"[\n, Fahrzeug-Nummer: AM-95365, , Ehem. UPE 2...","[\nAudi A1: , - 1e eigenaar , - Perfecte staat...","[\n, Technik & Sicherheit:, Xenon plus, Klimaa..."
Emission Label,NaN,[\n4 (Green)\n],[\n4 (Green)\n],NaN,NaN
Gears,NaN,[\n7\n],NaN,[\n6\n],NaN
Country version,NaN,NaN,NaN,NaN,[\nGermany\n]
Electricity consumption,NaN,NaN,NaN,NaN,NaN
Last Service Date,NaN,NaN,NaN,NaN,NaN
Other Fuel Types,NaN,NaN,NaN,NaN,NaN
Availability,NaN,NaN,NaN,NaN,NaN
Last Timing Belt Service Date,NaN,NaN,NaN,NaN,NaN
Available from,NaN,NaN,NaN,NaN,NaN

In [323]:
df.describe(include=object).T

,count,unique,top,freq
url,15919,15919,https://www.autoscout24.com//offers/audi-a1-sp...,1
make_model,15919,9,Audi A3,3097
short_description,15873,10001,SPB 1.6 TDI 116 CV S tronic Sport,64
body_type,15859,9,Sedans,7903
vat,11406,2,VAT deductible,10980
km,15919,6690,10 km,1045
registration,15919,48,-/-,1597
prev_owner,9091,4,1 previous owner,8294
hp,15919,81,85 kW,2542
Type,15917,169,"[, Used, , Diesel (Particulate Filter)]",3475
Previous Owners,9279,102,\n1\n,8101
Next Inspection,3535,1399,\n04/2022\n,62
Inspection new,3932,202,"[\nYes\n, \nEuro 6\n]",523
Warranty,10499,515,"[\n, \n, \nEuro 6\n]",1868
Full Service,8215,122,"[\n, \n, \n4 (Green)\n]",2235
Non-smoking Vehicle,7177,94,"[\n, \n]",3647
null,15919,1,[],15919
Make,15919,3,\nOpel\n,7343
Model,15919,9,"[\n, A3, \n]",3097
Offer Number,12744,11440,[\nLT67679\n],27
First Registration,14322,4,"[\n, 2018, \n]",4522
Body Color,15322,14,"[\n, Black, \n]",3745
Paint Type,10147,3,[\nMetallic\n],9794
Body Color Original,12160,1927,[\nOnyx Schwarz\n],338
Upholstery,12199,46,"[\nCloth, Black\n]",5821
Body,15859,9,"[\n, Sedans, \n]",7903
Nr. of Doors,15707,6,[\n5\n],11575
Nr. of Seats,14942,6,[\n5\n],13336
Model Code,4978,232,[\n0035/BCB\n],268
Gearing Type,15919,3,"[\n, Manual, \n]",8153
Displacement,15423,77,"[\n1,598 cc\n]",4761
Cylinders,10239,7,[\n4\n],8105
Weight,8945,434,"[\n1,163 kg\n]",574
Drive chain,9061,3,[\nfront\n],8886
Fuel,15919,77,"[\n, Diesel (Particulate Filter), \n]",4315
Consumption,14013,881,"[[3.9 l/100 km (comb)], [4.1 l/100 km (city)],...",304
CO2 Emission,14111,123,[\n120 g CO2/km (comb)\n],740
Emission Class,12898,7,[\nEuro 6\n],10139
\nComfort & Convenience\n,14999,6198,"[Air conditioning, Electrical side mirrors, Hi...",216
\nEntertainment & Media\n,14545,346,"[Bluetooth, Hands-free equipment, On-board com...",1282
\nExtras\n,12957,659,[Alloy wheels],3245
\nSafety & Security\n,14937,4443,"[ABS, Central door lock, Daytime running light...",538
description,15919,12874,[],636
Emission Label,3985,6,[\n4 (Green)\n],3553
Gears,11207,10,[\n6\n],5822
Country version,7586,23,[\nGermany\n],4502
Electricity consumption,137,1,[\n0 kWh/100 km (comb)\n],137
Last Service Date,566,266,"[\n02/2019\n, \nEuro 6\n]",23
Other Fuel Types,880,1,"[[], [], []]",880
Availability,635,15,\nin 90 days from ordering\n,196
Last Timing Belt Service Date,16,15,[\n04/2016\n],2
Available from,272,46,\n31/08/19\n,98

In [324]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 54 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   url                            15919 non-null  object
 1   make_model                     15919 non-null  object
 2   short_description              15873 non-null  object
 3   body_type                      15859 non-null  object
 4   price                          15919 non-null  int64
 5   vat                            11406 non-null  object
 6   km                             15919 non-null  object
 7   registration                   15919 non-null  object
 8   prev_owner                     9091 non-null   object
 9   kW                             0 non-null      float64
 10  hp                             15919 non-null  object
 11  Type                           15917 non-null  object
 12  Previous Owners                9279 non-null   object
 13  Next Inspection                3535 non-null   object
 14  Inspection new                 3932 non-null   object
 15  Warranty                       10499 non-null  object
 16  Full Service                   8215 non-null   object
 17  Non-smoking Vehicle            7177 non-null   object
 18  null                           15919 non-null  object
 19  Make                           15919 non-null  object
 20  Model                          15919 non-null  object
 21  Offer Number                   12744 non-null  object
 22  First Registration             14322 non-null  object
 23  Body Color                     15322 non-null  object
 24  Paint Type                     10147 non-null  object
 25  Body Color Original            12160 non-null  object
 26  Upholstery                     12199 non-null  object
 27  Body                           15859 non-null  object
 28  Nr. of Doors                   15707 non-null  object
 29  Nr. of Seats                   14942 non-null  object
 30  Model Code                     4978 non-null   object
 31  Gearing Type                   15919 non-null  object
 32  Displacement                   15423 non-null  object
 33  Cylinders                      10239 non-null  object
 34  Weight                         8945 non-null   object
 35  Drive chain                    9061 non-null   object
 36  Fuel                           15919 non-null  object
 37  Consumption                    14013 non-null  object
 38  CO2 Emission                   14111 non-null  object
 39  Emission Class                 12898 non-null  object
 40
Comfort & Convenience
        14999 non-null  object
 41
Entertainment & Media
        14545 non-null  object
 42
Extras
                       12957 non-null  object
 43
Safety & Security
            14937 non-null  object
 44  description                    15919 non-null  object
 45  Emission Label                 3985 non-null   object
 46  Gears                          11207 non-null  object
 47  Country version                7586 non-null   object
 48  Electricity consumption        137 non-null    object
 49  Last Service Date              566 non-null    object
 50  Other Fuel Types               880 non-null    object
 51  Availability                   635 non-null    object
 52  Last Timing Belt Service Date  16 non-null     object
 53  Available from                 272 non-null    object
dtypes: float64(1), int64(1), object(52)
memory usage: 6.6+ MB

In [325]:
(df.isnull().sum() / len(df)) * 100

url                                0.000000
make_model                         0.000000
short_description                  0.288963
body_type                          0.376908
price                              0.000000
vat                               28.349771
km                                 0.000000
registration                       0.000000
prev_owner                        42.892141
kW                               100.000000
hp                                 0.000000
Type                               0.012564
Previous Owners                   41.711163
Next Inspection                   77.793831
Inspection new                    75.299956
Warranty                          34.047365
Full Service                      48.395000
Non-smoking Vehicle               54.915510
null                               0.000000
Make                               0.000000
Model                              0.000000
Offer Number                      19.944720
First Registration                10.032037
Body Color                         3.750236
Paint Type                        36.258559
Body Color Original               23.613292
Upholstery                        23.368302
Body                               0.376908
Nr. of Doors                       1.331742
Nr. of Seats                       6.137320
Model Code                        68.729192
Gearing Type                       0.000000
Displacement                       3.115774
Cylinders                         35.680633
Weight                            43.809285
Drive chain                       43.080596
Fuel                               0.000000
Consumption                       11.973114
CO2 Emission                      11.357497
Emission Class                    18.977323
\nComfort & Convenience\n          5.779257
\nEntertainment & Media\n          8.631195
\nExtras\n                        18.606696
\nSafety & Security\n              6.168729
description                        0.000000
Emission Label                    74.967021
Gears                             29.599849
Country version                   52.346253
Electricity consumption           99.139393
Last Service Date                 96.444500
Other Fuel Types                  94.472015
Availability                      96.011056
Last Timing Belt Service Date     99.899491
Available from                    98.291350
dtype: float64

In [326]:
df.rename(columns = {'\nComfort & Convenience\n':'Comfort & Convenience', 
                     '\nEntertainment & Media\n':'Entertainment & Media',
                     '\nExtras\n':'Extras',
                     '\nSafety & Security\n':'Safety & Security'}, inplace = True)

In [327]:
df.columns = df.columns.str.replace(' ', '_')
df.T

,0,1,2,3,4,5,6,7,8,9,...,15909,15910,15911,15912,15913,15914,15915,15916,15917,15918
url,https://www.autoscout24.com//offers/audi-a1-sp...,https://www.autoscout24.com//offers/audi-a1-1-...,https://www.autoscout24.com//offers/audi-a1-sp...,https://www.autoscout24.com//offers/audi-a1-1-...,https://www.autoscout24.com//offers/audi-a1-sp...,https://www.autoscout24.com//offers/audi-a1-1-...,https://www.autoscout24.com//offers/audi-a1-sp...,https://www.autoscout24.com//offers/audi-a1-sp...,https://www.autoscout24.com//offers/audi-a1-sp...,https://www.autoscout24.com//offers/audi-a1-sp...,...,https://www.autoscout24.com//offers/renault-es...,https://www.autoscout24.com//offers/renault-es...,https://www.autoscout24.com//offers/renault-es...,https://www.autoscout24.com//offers/renault-es...,https://www.autoscout24.com//offers/renault-es...,https://www.autoscout24.com//offers/renault-es...,https://www.autoscout24.com//offers/renault-es...,https://www.autoscout24.com//offers/renault-es...,https://www.autoscout24.com//offers/renault-es...,https://www.autoscout24.com//offers/renault-es...
make_model,Audi A1,Audi A1,Audi A1,Audi A1,Audi A1,Audi A1,Audi A1,Audi A1,Audi A1,Audi A1,...,Renault Espace,Renault Espace,Renault Espace,Renault Espace,Renault Espace,Renault Espace,Renault Espace,Renault Espace,Renault Espace,Renault Espace
short_description,Sportback 1.4 TDI S-tronic Xenon Navi Klima,1.8 TFSI sport,Sportback 1.6 TDI S tronic Einparkhilfe plus+m...,1.4 TDi Design S tronic,Sportback 1.4 TDI S-Tronic S-Line Ext. admired...,1.6 TDI Sport DSG *SHZ*Xenon*Navi*Bose*PDC*,Sportback 1.6 TDI S-TRONIC S-LINE*NAVI|XENON*,Sportback 1.4 TDI admired S tronic,SPB 1.6 TDI S-tronic Metal plus + Xeno,SPORTBACK TFSI ULTRA 95 S-TRONIC AMB.,...,Limited Blue dCi 200 EDC,TCe 225 EDC INITIALE PDC SHZ BOSE KLIMA,ELYSEE ENERGY dCi 160 EDC,Blue dCi 200CV EDC Executive 4Control,INITIALE Paris TCe 225 EDC GPF ACC EU6,Blue dCi 200CV EDC Executive 4Control,"TCe 225 EDC GPF LIM Deluxe Pano,RFK",Blue dCi 200 EDC Initiale Paris Leder LED Navi...,"Blue dCi 200CV EDC Business , NUOVA DA IMMATRI...",INITIALE PARIS TCe 225 EDC GPF NAVI SHZ AUX
body_type,Sedans,Sedans,Sedans,Sedans,Sedans,Sedans,Station wagon,Compact,Sedans,Sedans,...,Van,Van,Van,Van,Van,Van,Van,Van,Van,Van
price,15770,14500,14640,14500,16790,15090,16422,14480,16700,17990,...,39990,39980,39980,39950,39950,39950,39885,39875,39700,40999
vat,VAT deductible,Price negotiable,VAT deductible,None,None,None,VAT deductible,VAT deductible,None,None,...,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible
km,"56,013 km","80,000 km","83,450 km","73,000 km","16,200 km","63,668 km","62,111 km","14,986 km","57,000 km","16,103 km",...,"3,500 km","8,500 km",100 km,- km,"1,000 km",- km,"9,900 km",15 km,10 km,- km
registration,01/2016,03/2017,02/2016,08/2016,05/2016,02/2016,03/2016,02/2016,02/2016,06/2017,...,05/2019,02/2019,02/2019,-/-,04/2019,-/-,01/2019,03/2019,06/2019,01/2019
prev_owner,2 previous owners,None,1 previous owner,1 previous owner,1 previous owner,1 previous owner,1 previous owner,1 previous owner,1 previous owner,None,...,None,1 previous owner,1 previous owner,None,None,None,1 previous owner,1 previous owner,None,1 previous owner
kW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hp,66 kW,141 kW,85 kW,66 kW,66 kW,85 kW,85 kW,66 kW,85 kW,70 kW,...,147 kW,165 kW,118 kW,147 kW,165 kW,147 kW,165 kW,146 kW,147 kW,165 kW
Type,"[, Used, , Diesel (Particulate Filter)]","[, Used, , Gasoline]","[, Used, , Diesel (Particulate Filter)]","[, Used, , Diesel (Particulate Filter)]","[, Used, , Diesel (Particulate Filter)]","[, Used, , Diesel (Particulate Filter)]","[, Used, , Diesel (Particulate Filter)]","[, Used, , Diesel (Particulate Filter)]","[, Used, , Diesel (Particulate Filter)]","[, Used, , Gasoline]",...,"[, Demonstration, , Diesel (Particulate Filter)]","[, Demonstration, , Regular/Benzine E10 91]","[, Pre-registered, , Diesel (Particulate Filter)]","[, New, , Diesel (Particulate Filter)]","[, Demonstration, , Super 95]","[, New, , Diesel (Particulate Filter)]","[, Used, , Super 95 / Super Plus 98 (Particula...","[, Pre-registered, , Diesel]","[, Pre-registered, , Diesel]","[, Demonstration, , Super 95]"
Previous_Owners,\n2\n,NaN,\n1\n,\n1\n,\n1\n,\n1\n,\n1\n,\n1\n,\n1\n,NaN,...,NaN,\n1\n,\n1\n,NaN,NaN,NaN,"[\n1\n, \n, 7.4 l/100 km (comb), \n, 9.2 l/100...","[\n1\n, \n139 g CO2/km (comb)\n]",NaN,\n1\n
Next_Inspection,"[\n06/2021\n, \n99 g CO2/km (comb)\n]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[\n02/2020\n, \n97 g CO2/km (comb)\n]",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[\n01/2022\n, \n168 g CO2/km (comb)\n]",NaN,NaN,NaN
Inspection_new,"[\nYes\n, \nEuro 6\n]",NaN,NaN,NaN,"[\nYes\n, \n109 g CO2/km (comb)\n]",NaN,"[\nYes\n, \n98 g CO2/km (comb)\n]","[\nYes\n, \n97 g CO2/km (comb)\n]",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[\nYes\n, \nEuro 6d-TEMP\n]",NaN,"[\nYes\n, \n153 g CO2/km (comb)\n]"
Warranty,"[\n, \n, \n4 (Green)\n]",NaN,"[\n, \n, \n99 g CO2/km (comb)\n]",NaN,"[\n, \n, \nEuro 6\n]",NaN,NaN,"[\n, \n, \nEuro 6\n]","[\n12 months\n, \nEuro 6\n]",\n3 months\n,...,\n48 months\n,NaN,NaN,\n24 months\n,NaN,\n24 months\n,"[\n, \n, \nEuro 6\n]","[\n, \n, \n4 (Green)\n]",\n,NaN
Full_Service,"[\n, \n]",NaN,NaN,"[\n, \n, \n99 g CO2/km (comb)\n]","[\n, \n, \n4 (Green)\n]","[\n, \n, \n92 g CO2/km (comb)\n]","[\n, \n, \nEuro 6\n]","[\n, \n, \n4 (Green)\n]",NaN,NaN,...,NaN,"[\n, \n, \n153 g CO2/km (comb)\n]",NaN,NaN,NaN,NaN,NaN,"[\n, \n]",NaN,NaN
Non-smoking_Vehicle,"[\n, \n]",NaN,NaN,"[\n, \n, \nEuro 6\n]","[\n, \n]","[\n, \n, \nEuro 6\n]","[\n, \n, \n4 (Green)\n]",NaN,NaN,NaN,...,NaN,"[\n, \n, \nEuro 6\n]","[\n, \n, \n123 g CO2/km (comb)\n]",NaN,NaN,NaN,"[\n, \n, \n4 (Green)\n]","[\n, \n]",NaN,NaN
null,[],[],[],[],[],[],[],[],[],[],...,[],[],[],[],[],[],[],[],[],[]
Make,\nAudi\n,\nAudi\n,\nAudi\n,\nAudi\n,\nAudi\n,\nAudi\n,\nAudi\n,\nAudi\n,\nAudi\n,\nAudi\n,...,\nRenault\n,\nRenault\n,\nRenault\n,\nRenault\n,\nRenault\n,\nRenault\n,\nRenault\n,\nRenault\n,\nRenault\n,\nRenault\n
Model,"[\n, A1, \n]","[\n, A1, \n]","[\n, A1, \n]","[\n, A1, \n]","[\n, A1, \n]","[\n, A1, \n]","[\n, A1, \n]","[\n, A1, \n]","[\n, A1, \n]","[\n, A1, \n]",...,"[\n, Espace, \n]","[\n, Espace, \n]","[\n, Espace, \n]","[\n, Espace, \n]","[\n, Espace, \n]","[\n, Espace, \n]","[\n, Espace, \n]","[\n, Espace, \n]","[\n, Espace, \n]","[\n, Espace, \n]"
Offer_Number,[\nLR-062483\n],NaN,[\nAM-95365\n],NaN,[\nC1626\n],[\nJV03654\n],[\n200-19\n],[\n18381A-Q2\n],[\n11540324\n],NaN,...,[\n1-15447\n],[\n1720LR8\n],[\nVB1_12468\n],[\n10988276\n],[\nNW9766\n],[\n10988301\n],[\n507370_3223\n],[\nEspace16\n],[\n2691331\n],[\nRe_30000008029\n]
First_Registration,"[\n, 2016, \n]","[\n, 2017, \n]","[\n, 2016, \n]","[\n, 2016, \n]","[\n, 2016, \n]","[\n, 2016, \n]","[\n, 2016, \n]","[\n, 2016, \n]","[\n, 2016, \n]","[\n, 2017, \n]",...,"[\n, 2019, \n]","[\n, 2019, \n]","[\n, 2019, \n]",NaN,"[\n, 2019, \n]",NaN,"[\n, 2019, \n]","[\n, 2019, \n]","[\n, 2019, \n]","[\n, 2019, \n]"
Body_Color,"[\n, Black, \n]","[\n, Red, \n]","[\n, Black, \n]","[\n, Brown, \n]","[\n, Black, \n]","[\n, White, \n]","[\n, White, \n]","[\n, Red, \n]","[\n, Grey, \n]","[\n, White, \n]",...,"[\n, Black, \n]","[\n, Blue, \n]","[\n, White, \n]","[\n, Black, \n]","[\n, White, \n]","[\n, Grey, \n]","[\n, Grey, \n]","[\n, White, \n]","[\n, Grey, \n]","[\n, Grey, \n]"
Paint_Type,[\nMetallic\n],NaN,[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],NaN,...,[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],NaN,NaN,[\nMetallic\n]
Body_Color_Original,[\nMythosschwarz\n],NaN,[\nmythosschwarz metallic\n],NaN,[\nMythosschwarz Metallic\n],NaN,[\nGletscherweiss\n],[\nMisanorot Perleffekt\n],[\nGrigio\n],[\nBlanc\n],...,[\nBlack-Pearl\n],[\nKosmos-Blau\n],[\nPerlmutt-Wei√ü Metallic (Wei√ü)\n],[\nNero\n],[\nperlmutt-weiss\n],[\nGrigio scuro\n],[\nStahl-Grau Metallic\n],[\narktis-wei√ü\n],[\nGrigio\n],[\nTitanium-Grau Metallic\n]
Upholstery,"[\nCloth, Black\n]","[\nCloth, Grey\n]","[\nCloth, Black\n]",NaN,"[\nCloth, Black\n]","[\nPart leather, Black\n]","[\nPart leather, Black\n]","[\nCloth, Black\n]","[\nCloth, Grey\n]",NaN,...,NaN,"[\nFull leather, Other\n]","[\nFull leather, Grey\n]",NaN,"[\nFull leather, Brown\n]",NaN,[\nCloth\n],"[\nFull leather, Black\n]",[\nPart leather\n],"[\nFull leather, Brown\n]"
Body,"[\n, Sedans, \n]","[\n, Sedans, \n]","[\n, Sedans, \n]","[\n, Sedans, \n]","[\n, Sedans, \n]","[\n, Sedans, \n]","[\n, Station wagon, \n]","[\n, Compact, \n]","[\n, Sedans, \n]","[\n, Sedans, \n]",...,"[\n, Van, \n]","[\n, Van, \n]","[\n, Van, \n]","[\n, Van, \n]","[\n, Van, \n]","[\n, Van, \n]","[\n, Van, \n]","[\n, Van, \n]","[\n, Van, \n]","[\n, Van, \n]"
Nr._of_Doors,[\n5\n],[\n3\n],[\n4\n],[\n3\n],[\n5\n],[\n4\n],[\n4\n],[\n5\n],[\n5\n],[\n5\n],...,[\n5\n],[\n5\n],[\n5\n],[\n5\n],[\n5\n],[\n5\n],[\n5\n],[\n5\n],[\n5\n],[\n5\n]
Nr._of_Seats,[\n5\n],[\n4\n],[\n4\n],[\n4\n],[\n5\n],[\n5\n],[\n5\n],[\n5\n],[\n4\n],[\n4\n],...,[\n5\n],[\n5\n],[\n7\n],[\n5\n],[\n7\n],[\n5\n],[\n5\n],[\n7\n],[\n7\n],[\n5\n]
Model_Code,[\n0588/BDF\n],[\n0588/BCY\n],NaN,NaN,[\n0588/BDF\n],NaN,NaN,[\n0588/BDF\n],NaN,NaN,...,NaN,[\n3333/BHJ\n],[\n3333/BDQ\n],NaN,NaN,NaN,[\n0000/000\n],NaN,NaN,[\n3333/BHJ\n]
Gearing_Type,"[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]",...,"[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]"
Displacement,"[\n1,422 cc\n]","[\n1,798 cc\n]","[\n1,598 cc\n]","[\n1,422 cc\n]","[\n1,422 cc\n]","[\n1,598 cc\n]","[\n1,598 cc\n]","[\n1,422 cc\n]","[\n1,598 cc\n]",[\n999 cc\n],...,"[\n1,997 cc\n]","[\n1,798 cc\n]","[\n1,598 cc\n]","[\n1,997 cc\n]","[\n1,798 cc\n]","[\n1,997 cc\n]","[\n1,798 cc\n]","[\n1,997 cc\n]","[\n1,997 cc\n]","[\n1,798 cc\n]"
Cylinders,[\n3\n],[\n4\n],NaN,[\n3\n],[\n3\n],NaN,[\n4\n],NaN,[\n4\n],NaN,...,NaN,[\n4\n],[\n4\n],[\n4\n],[\n4\n],[\n4\n],[\n4\n],[\n4\n],[\n4\n],[\n4\n]
Weight,"[\n1,220 kg\n]","[\n1,255 kg\n]",NaN,"[\n1,195 kg\n]",NaN,NaN,NaN,NaN,"[\n1,275 kg\n]",NaN,...,"[\n1,779 kg\n]",NaN,"[\n1,734 kg\n]","[\n1,758 kg\n]",NaN,"[\n1,758 kg\n]","[\n1,708 kg\n]",NaN,"[\n1,758 kg\n]","[\n1,685 kg\n]"
Drive_chain,[\nfront\n],[\nfront\n],[\nfront\n],NaN,[\nfront\n],NaN,[\nfront\n],[\nfront\n],[\nfront\n],NaN,...,NaN,[\nfront\n],NaN,[\nfront\n],[\nfront\n],[\nfront\n],[\nfront\n],[\nfront\n],[\nfront\n],[\n4WD\n]
Fuel,"[\n, Diesel (Particulate Filter), \n]","[\n, Gasoline, \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Gasoline, \n]",...,"[\n, Diesel (Particulate Filter), \n]","[\n, Regular/Benzine E10 91, \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Super 95, \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Super 95 / Super Plus 98 (Particulate Fil...","[\n, Diesel, \n]","[\n, Diesel, \n]","[\n, Super 95, \n]"
Consumption,"[[3.8 l/100 km (comb)], [4.3 l/100 km (city)],...","[[5.6 l/100 km (comb)], [7.1 l/100 km (city)],...","[[3.8 l/100 km (comb)], [4.4 l/100 km (city)],...","[[3.8 l/100 km (comb)], [4.3 l/100 km (city)],...","[[4.1 l/100 km (comb)], [4.6 l/100 km (city)],...","[[3.5 l/100 km (comb)], [4.3 l/100 km (city)],...","[[3.7 l/100 km (comb)], [4.3 l/100 km (city)],...","[[3.7 l/100 km (comb)], [4.2 l/100 km (city)],...","[[3.7 l/100 km (comb)], [4.3 l/100 km (city)],...",NaN,...,NaN,"[[6 l/100 km (comb)], [8 l/100 km (city)], [5 ...","[[4.7 l/100 km (comb)], [5.1 l/100 km (city)],...","[[5.3 l/100 km (comb)], [6.2 l/100 km (city)],...","[[6.8 l/100 km (comb)], [8.7 l/100 km (city)],...","[[5.3 l/100 km (comb)], [6.2 l/100 km (city)],...","[\n, 7.4 l/100 km (comb), \n, 9.2 l/100 km (ci...","[[5.3 l/100 km (comb)], [6.2 l/100 km (city)],...","[[5.3 l/100 km (comb)], [6.2 l/100 km (city)],...","[[6.8 l/100 km (comb)], [8.7 l/100 km (city)],..."
CO2_Emission,[\n99 g CO2/km (comb)\n],[\n129 g CO2/km (comb)\n],[\n99 g CO2/km (comb)\n],[\n99 g CO2/km (comb)\n],[\n109 g CO2/km (comb)\n],[\n92 g CO2/km (comb)\n],[\n98 g CO2/km (comb)\n],[\n97 g CO2/km (comb)\n],[\n97 g CO2/km (comb)\n],NaN,...,"[[], [], []]",[\n153 g CO2/km (comb)\n],[\n123 g CO2/km (comb)\n],[\n139 g CO2/km (comb)\n],[\n153 g CO2/km (comb)\n],[\n139 g CO2/km (comb)\n],[\n168 g CO2/km (comb)\n],[\n139 g CO2/km (comb)\n],[\n139 g CO2/km (comb)\n],[\n153 g CO2/km (comb)\n]
Emission_Class,[\nEuro 6\n],[\nEuro 6\n],[\nEuro 6\n],[\nEuro 6\n],[\nEuro 6\n],[\nEuro 6\n],[\nEuro 6\n],[\nEuro 6\n],[\nEuro 6\n],NaN,...,NaN,[\nEuro 6\n],[\nEuro 6\n],NaN,[\nEuro 6\n],NaN,NaN,[\nEuro 6d-TEMP\n],[\nEuro 6\n],[\nEuro 6\n]
Comfort_&_Convenience,"[Air conditioning, Armrest, Automatic climate ...","[Air conditioning, Automatic climate control, ...","[Air conditioning, Cruise control, Electrical ...","[Air suspension, Armrest, Auxiliary heating, E...","[Air conditioning, Armrest, Automatic climate ...","[Air conditioning, Armrest, Automatic climate ...","[Air conditioning, Armrest, Automatic climate ...","[Air conditioning, Armrest, Electrical side mi...","[Air conditioning, Power windows]",NaN,...,"[Air conditioning, Automatic climate control, ...","[Air conditioning, Automatic climate control, ...","[Air conditioning, Armrest, Automatic climate ...","[Air conditioning, Automatic climate control, ...","[Air conditioning, Armrest, Automatic climate ...","[Air conditioning, Automatic climate control, ...","[Air conditioning, Automatic climate control, ...","[Air conditioning, Armrest, Automatic climate ...","[Air conditioning, Automatic climate control, ...","[Air conditioning, Automatic climate control, ..."
Entertainment_&_Media,"[Bluetooth, Hands-free equipment, On-board com...","[Bluetooth, Hands-free equipment, On-board com...","[MP3, On-board computer]","[Bluetooth, CD player, Hands-free equipment, M...","[Bluetooth, CD player, Hands-free equipment, M...","[Bluetooth, Hands-free equipment, On-board com...","[Bluetooth, CD player, Hands-free equipment, O...","[CD player, MP3, Radio]",[Radio],NaN,...,"[Bluetooth, Hands-free equipment, On-board com...","[Bluetooth, Hands-free equipment, On-board com...","[Bluetooth, Digital radio, Hands-free equipmen...","[Bluetooth, Digital radio, Hands-free equipmen...","[Bluetooth, Digital radio, Hands-free equipmen...","[Bluetooth, Digital radio, Hands-free equipmen...","[Bluetooth, Digital radio, Hands-free equipmen...","[Bluetooth, Hands-free equipment, On-board com...","[Bluetooth, Digital radio, Radio, USB]",[USB]
Extras,"[Alloy wheels, Catalytic Converter, Voice Cont...","[Alloy wheels, Sport seats, Sport suspension, ...","[Alloy wheels, Voice Control]","[Alloy wheels, Sport seats, Voice Control]","[Alloy wheels, Sport package, Sport suspension...","[Alloy wheels, Sport package, Sport seats, Spo...","[Alloy wheels, Sport package, Sport seats, Spo...",[Alloy wheels],[Alloy wheels],NaN,...,"[Alloy wheels, Touch screen]",[Alloy wheels],"[Alloy wheels, Touch screen, Voice Control]","[Alloy wheels, Touch screen]","[Alloy wheels, Catalytic Converter, Sport susp...","[Alloy wheels, Touch screen]","[Alloy wheels, Touch screen, Voice Control]",[Alloy wheels],"[Alloy wheels, Touch screen]","[Alloy wheels, Touch screen]"
Safety_&_Security,"[ABS, Central door lock, Daytime running light...","[ABS, Central door lock, Central door lock wit...","[ABS, Central door lock, Daytime running light...","[ABS, Alarm system, Central door lock with rem...","[ABS, Central door lock, Driver-side airbag, E...","[ABS, Central door lock, Daytime running light...","[ABS, Central door lock, Daytime running light...","[ABS, Central door lock, Daytime running light...","[ABS, Central door lock, Driver-side airbag, E...",NaN,...,"[ABS, Blind spot monitor, Central door lock, D...","[ABS, Adaptive headlights, Central door lock, ...","[ABS, Adaptive Cruise Control, Central door lo...","[ABS, Central door lock, Central door lock wit...","[ABS, Adaptive Cruise Control, Blind spot moni...","[ABS, Central door lock, Central door lock wit...","[ABS, Adaptive Cruise Control, Blind spot moni...","[ABS, Adaptive Cruise Control, Blind spot moni...","[ABS, Blind spot monitor, Driver-side airbag, ...","[ABS, Blind spot monitor, Daytime running ligh..."
description,"[\n, Sicherheit:, , Deaktivierung f√ºr Beifahr...",[\nLangstreckenfahrzeug daher die hohe Kilomet...,"[\n, Fahrzeug-Nummer: AM-95365, , Ehem. UPE 2...","[\nAudi A1: , - 1e eigenaar , - Perfecte staat...","[\n, Technik & Sicherheit:, Xenon plus, Klimaa...",[\nSichern Sie sich diesen Audi A1 1.6 TDI Spo...,"[\nREDUZIERT !!!, MwSt. ausweisbar, Nettopreis...","[\n, Ausstattungspakete:, Ausstattungspaket: ...",[\nAuto in ottime condizioni. Unico proprietar...,"[\nClim automatique,Ecran multifonction couleu...",...,"[\nHallo!, Das Beratungsteam der Fa. Sonnleitn...","[\n, Warum ist dieses Auto das Richtige f√ºr mi...","[\n, Komfort:, , abgedunkelte Scheiben im Fon...",[\nVettura visionabile nella sede in Via Roma ...,"[\nFahrzeug-Nr.: NW9766., Ausstattungslinie/ -...",[\nVettura visionabile nella sede in Via Roma ...,"[\nDach: Panorama-Glas-Schiebedach, Lackierung...","[\n, Getriebe:, Automatik, Technik:, Bordcom...","[\nDEK:[2691331], Renault Espace Blue dCi 200C...","[\n, Sicherheit Airbags:, , Seitenairbag, , ..."
Emission_Label,NaN,[\n4 (Green)\n],[\n4 (Green)\n],NaN,NaN,[\n4 (Green)\n],NaN,NaN,NaN,NaN,...,NaN,[\n4 (Green)\n],[\n4 (Green)\n],NaN,[\n4 (Green)\n],NaN,NaN,NaN,NaN,[\n4 (Green)\n]
Gears,NaN,[\n7\n],NaN,[\n6\n],NaN,NaN,NaN,[\n7\n],[\n7\n],[\n7\n],...,[\n7\n],[\n7\n],NaN,[\n6\n],NaN,[\n6\n],[\n7\n],[\n6\n],[\n6\n],NaN
Country_version,NaN,NaN,NaN,NaN,[\nGermany\n],[\nGermany\n],[\nGermany\n],NaN,NaN,NaN,...,[\nAustria\n],NaN,[\nGermany\n],NaN,NaN,NaN,[\nGermany\n],[\nAustria\n],NaN,[\nGermany\n]
Electricity_consumption,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Last_Service_Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Other_Fuel_Types,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[[], [], []]",NaN,NaN,NaN
Availability,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,\nin 5 days from ordering\n,\nin 120 days from ordering\n,NaN,NaN
Last_Timing_Belt_Service_Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Available_from,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Make, Model, Make_model

In [328]:
df.Make

0           \nAudi\n
1           \nAudi\n
2           \nAudi\n
3           \nAudi\n
4           \nAudi\n
            ...
15914    \nRenault\n
15915    \nRenault\n
15916    \nRenault\n
15917    \nRenault\n
15918    \nRenault\n
Name: Make, Length: 15919, dtype: object

In [329]:
df['Make'] = df['Make'].map(lambda x : x.strip('\n'), na_action = 'ignore')

In [330]:
df['Make'].value_counts

<bound method IndexOpsMixin.value_counts of 0           Audi
1           Audi
2           Audi
3           Audi
4           Audi
          ...
15914    Renault
15915    Renault
15916    Renault
15917    Renault
15918    Renault
Name: Make, Length: 15919, dtype: object>

In [331]:
df[['make_model', 'Make', 'Model']].sample(20)

           make_model     Make               Model
10471   Opel Insignia     Opel  [\n, Insignia, \n]
548           Audi A1     Audi        [\n, A1, \n]
5389          Audi A3     Audi        [\n, A3, \n]
2443          Audi A1     Audi        [\n, A1, \n]
15005  Renault Espace  Renault    [\n, Espace, \n]
11966   Opel Insignia     Opel  [\n, Insignia, \n]
9249       Opel Corsa     Opel     [\n, Corsa, \n]
9610       Opel Corsa     Opel     [\n, Corsa, \n]
15086  Renault Espace  Renault    [\n, Espace, \n]
5582          Audi A3     Audi        [\n, A3, \n]
7146       Opel Astra     Opel     [\n, Astra, \n]
1225          Audi A1     Audi        [\n, A1, \n]
1903          Audi A1     Audi        [\n, A1, \n]
2913          Audi A3     Audi        [\n, A3, \n]
1138          Audi A1     Audi        [\n, A1, \n]
11857   Opel Insignia     Opel  [\n, Insignia, \n]
7785       Opel Astra     Opel     [\n, Astra, \n]
8414       Opel Corsa     Opel     [\n, Corsa, \n]
15552  Renault Espace  Renault    [\n, Espace, \n]
3477          Audi A3     Audi        [\n, A3, \n]

In [332]:
df.make_model.unique()

array(['Audi A1', 'Audi A2', 'Audi A3', 'Opel Astra', 'Opel Corsa',
       'Opel Insignia', 'Renault Clio', 'Renault Duster',
       'Renault Espace'], dtype=object)

In [333]:
df.make_model.value_counts()

Audi A3           3097
Audi A1           2614
Opel Insignia     2598
Opel Astra        2526
Opel Corsa        2219
Renault Clio      1839
Renault Espace     991
Renault Duster      34
Audi A2              1
Name: make_model, dtype: int64

In [334]:
df.make_model.isnull().sum()

0

In [335]:
df.columns

Index(['url', 'make_model', 'short_description', 'body_type', 'price', 'vat',
       'km', 'registration', 'prev_owner', 'kW', 'hp', 'Type',
       'Previous_Owners', 'Next_Inspection', 'Inspection_new', 'Warranty',
       'Full_Service', 'Non-smoking_Vehicle', 'null', 'Make', 'Model',
       'Offer_Number', 'First_Registration', 'Body_Color', 'Paint_Type',
       'Body_Color_Original', 'Upholstery', 'Body', 'Nr._of_Doors',
       'Nr._of_Seats', 'Model_Code', 'Gearing_Type', 'Displacement',
       'Cylinders', 'Weight', 'Drive_chain', 'Fuel', 'Consumption',
       'CO2_Emission', 'Emission_Class', 'Comfort_&_Convenience',
       'Entertainment_&_Media', 'Extras', 'Safety_&_Security', 'description',
       'Emission_Label', 'Gears', 'Country_version', 'Electricity_consumption',
       'Last_Service_Date', 'Other_Fuel_Types', 'Availability',
       'Last_Timing_Belt_Service_Date', 'Available_from'],
      dtype='object')

In [336]:
df[['body_type', 'Body']].sample(20)

           body_type                     Body
2443          Sedans         [\n, Sedans, \n]
3545          Sedans         [\n, Sedans, \n]
7771          Sedans         [\n, Sedans, \n]
11786  Station wagon  [\n, Station wagon, \n]
2440          Sedans         [\n, Sedans, \n]
10523  Station wagon  [\n, Station wagon, \n]
3249          Sedans         [\n, Sedans, \n]
10854  Station wagon  [\n, Station wagon, \n]
4417          Sedans         [\n, Sedans, \n]
11054         Sedans         [\n, Sedans, \n]
5525          Sedans         [\n, Sedans, \n]
11171  Station wagon  [\n, Station wagon, \n]
8842         Compact        [\n, Compact, \n]
12631         Sedans         [\n, Sedans, \n]
14340         Sedans         [\n, Sedans, \n]
12133  Station wagon  [\n, Station wagon, \n]
3606          Sedans         [\n, Sedans, \n]
15419    Transporter    [\n, Transporter, \n]
4752          Sedans         [\n, Sedans, \n]
2716   Station wagon  [\n, Station wagon, \n]

In [337]:
df.price.isnull().sum()

0

In [338]:
df[df.price == 'nan'].value_counts().sum()

0

In [339]:
df.vat.unique()

array(['VAT deductible', 'Price negotiable', None], dtype=object)

In [340]:
df.vat.nunique()

2

In [341]:
df.vat.value_counts(dropna=False)

VAT deductible      10980
NaN                  4513
Price negotiable      426
Name: vat, dtype: int64

In [342]:
df.vat.isnull().sum()

4513

In [343]:
df.km.unique()

array(['56,013 km', '80,000 km', '83,450 km', ..., '2,864 km', '1,506 km',
       '57 km'], dtype=object)

In [344]:
df.km.nunique()

6690

In [345]:
df.km.value_counts(dropna=False)

10 km        1045
- km         1024
1 km          367
5 km          170
50 km         148
             ...
67,469 km       1
43,197 km       1
10,027 km       1
35,882 km       1
57 km           1
Name: km, Length: 6690, dtype: int64

In [346]:
df.km.isnull().sum()

0

In [347]:
df[['km']]

              km
0      56,013 km
1      80,000 km
2      83,450 km
3      73,000 km
4      16,200 km
...          ...
15914       - km
15915   9,900 km
15916      15 km
15917      10 km
15918       - km

[15919 rows x 1 columns]

In [348]:
df.km.str.replace(',','')

0        56013 km
1        80000 km
2        83450 km
3        73000 km
4        16200 km
           ...
15914        - km
15915     9900 km
15916       15 km
15917       10 km
15918        - km
Name: km, Length: 15919, dtype: object

In [349]:
df['km'] = df.km.str.replace(',', '').str.strip(' km').replace('-', np.nan).astype(float)

In [350]:
df['km']

0        56013.0
1        80000.0
2        83450.0
3        73000.0
4        16200.0
          ...
15914        NaN
15915     9900.0
15916       15.0
15917       10.0
15918        NaN
Name: km, Length: 15919, dtype: float64

In [351]:
df[['registration', 'First_Registration']].isnull().sum()

registration             0
First_Registration    1597
dtype: int64

In [352]:
df[['registration', 'First_Registration']].sample(5)

      registration First_Registration
14338      01/2018     [\n, 2018, \n]
2067       03/2019     [\n, 2019, \n]
15770          -/-                NaN
9010       05/2016     [\n, 2016, \n]
14320      06/2018     [\n, 2018, \n]

In [353]:
df['registration'].head()

0    01/2016
1    03/2017
2    02/2016
3    08/2016
4    05/2016
Name: registration, dtype: object

In [354]:
df['registration'].value_counts()

-/-        1597
03/2018     695
02/2019     585
05/2018     572
03/2019     543
01/2019     541
04/2018     541
02/2018     539
03/2016     536
04/2016     532
06/2018     532
01/2018     511
04/2019     506
02/2016     472
03/2017     471
05/2016     459
06/2016     452
05/2019     440
06/2017     409
05/2017     404
07/2018     396
04/2017     380
01/2016     376
02/2017     368
01/2017     306
08/2018     285
06/2019     224
07/2017     215
11/2017     180
07/2016     176
10/2016     160
10/2017     154
09/2017     149
11/2016     142
09/2018     141
09/2016     141
12/2016     134
12/2017     123
08/2017     114
11/2018     110
12/2018     103
10/2018      97
08/2016      94
07/2019       6
09/2019       5
08/2019       1
11/2019       1
12/2019       1
Name: registration, dtype: int64

In [355]:
df['registration'].map(lambda x : x[3:], na_action= 'ignore')

0        2016
1        2017
2        2016
3        2016
4        2016
         ...
15914
15915    2019
15916    2019
15917    2019
15918    2019
Name: registration, Length: 15919, dtype: object

In [356]:
df['registration'] = df['registration'].map(lambda x : x[3:], na_action= 'ignore')

In [357]:
df['registration'] = pd.to_numeric(df['registration'], errors='coerce')

In [358]:
df.registration.sample(10)

10460    2016.0
6475     2018.0
7267     2018.0
5603     2019.0
10247    2019.0
13696    2016.0
13832    2017.0
11716    2017.0
2173     2019.0
8177     2019.0
Name: registration, dtype: float64

In [359]:
df['age']= 2019 - df['registration']
df['age']

0        3.0
1        2.0
2        3.0
3        3.0
4        3.0
        ...
15914    NaN
15915    0.0
15916    0.0
15917    0.0
15918    0.0
Name: age, Length: 15919, dtype: float64

In [360]:
df['age'].value_counts(dropna=False)

1.0    4522
3.0    3674
2.0    3273
0.0    2853
NaN    1597
Name: age, dtype: int64

In [361]:
df['prev_owner'].head(3)

0    2 previous owners
1                 None
2     1 previous owner
Name: prev_owner, dtype: object

In [362]:
df['prev_owner'].value_counts(dropna=False)

1 previous owner     8294
NaN                  6828
2 previous owners     778
3 previous owners      17
4 previous owners       2
Name: prev_owner, dtype: int64

In [363]:
df['prev_owner'].isnull().sum()

6828

In [364]:
df['prev_owner'].str.strip('previous owners').astype(float)

0        2.0
1        NaN
2        1.0
3        1.0
4        1.0
        ...
15914    NaN
15915    1.0
15916    1.0
15917    NaN
15918    1.0
Name: prev_owner, Length: 15919, dtype: float64

In [365]:
df['prev_owner'] = df.prev_owner.str.strip('previous owners').astype(float)

In [366]:
df['prev_owner'].value_counts(dropna=False)

1.0    8294
NaN    6828
2.0     778
3.0      17
4.0       2
Name: prev_owner, dtype: int64

In [367]:
df['Previous_Owners'].head(3)

0    \n2\n
1      NaN
2    \n1\n
Name: Previous_Owners, dtype: object

In [368]:
df['Previous_Owners'].value_counts(dropna=False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

\n1\n                                                                                        8101
NaN                                                                                          6640
\n2\n                                                                                         766
\n0\n                                                                                         163
\n3\n                                                                                          17
                                                                                             ...
[\n1\n, \n111 g CO2/km (comb)\n]                                                                1
[\n1\n, \nEuro 6\n]                                                                             1
[\n2\n, \n119 g CO2/km (comb)\n]                                                                1
[\n1\n, \n, 6.6 l/100 km (comb), \n, 8.1 l/100 km (city), \n, 5.7 l/100 km (country), \n]       1
[\n2\n, \n137 g CO2/km (comb)\n]                                                                1
Name: Previous_Owners, Length: 103, dtype: int64

In [369]:
df['Previous_Owners'].isnull().sum()

6640

In [370]:
df['Previous_Owners'].str.strip('\n').astype(float)

0        2.0
1        NaN
2        1.0
3        1.0
4        1.0
        ...
15914    NaN
15915    NaN
15916    NaN
15917    NaN
15918    1.0
Name: Previous_Owners, Length: 15919, dtype: float64

In [371]:
df['Previous_Owners'].value_counts(dropna=False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

\n1\n                                                                                        8101
NaN                                                                                          6640
\n2\n                                                                                         766
\n0\n                                                                                         163
\n3\n                                                                                          17
                                                                                             ...
[\n1\n, \n111 g CO2/km (comb)\n]                                                                1
[\n1\n, \nEuro 6\n]                                                                             1
[\n2\n, \n119 g CO2/km (comb)\n]                                                                1
[\n1\n, \n, 6.6 l/100 km (comb), \n, 8.1 l/100 km (city), \n, 5.7 l/100 km (country), \n]       1
[\n2\n, \n137 g CO2/km (comb)\n]                                                                1
Name: Previous_Owners, Length: 103, dtype: int64

In [372]:
df[['prev_owner', 'Previous_Owners']].isnull().sum()

prev_owner         6828
Previous_Owners    6640
dtype: int64

In [373]:
df[['prev_owner', 'Previous_Owners']].sample(10)

       prev_owner                   Previous_Owners
12967         NaN                               NaN
4118          NaN                               NaN
3995          NaN                               NaN
15489         1.0                             \n1\n
11543         1.0                             \n1\n
7358          NaN                               NaN
3816          1.0  [\n1\n, \n114 g CO2/km (comb)\n]
4630          NaN                               NaN
10059         1.0                             \n1\n
14297         1.0                             \n1\n

In [374]:
df.loc[(df['prev_owner'].isnull()) & (df['Previous_Owners'] == 0), 'prev_owner'] = 0

In [375]:
df['prev_owner'].value_counts(dropna=False)

1.0    8294
NaN    6828
2.0     778
3.0      17
4.0       2
Name: prev_owner, dtype: int64

In [376]:
df['kW'].head(3)

0   NaN
1   NaN
2   NaN
Name: kW, dtype: float64

In [377]:
df['kW'].isnull().sum()

15919

In [378]:
df['hp'].head(3)

0     66 kW
1    141 kW
2     85 kW
Name: hp, dtype: object

In [379]:
df['hp'].value_counts(dropna=False)

85 kW     2542
66 kW     2122
81 kW     1402
100 kW    1308
110 kW    1112
          ...
84 kW        1
195 kW       1
44 kW        1
239 kW       1
9 kW         1
Name: hp, Length: 81, dtype: int64

In [380]:
df['hp'].isnull().sum()

0

In [381]:
df['hp_kw'] = df['hp'].str.strip(' kW').replace('-', np.nan).astype(float)
df['hp_kw']

0         66.0
1        141.0
2         85.0
3         66.0
4         66.0
         ...
15914    147.0
15915    165.0
15916    146.0
15917    147.0
15918    165.0
Name: hp_kw, Length: 15919, dtype: float64

In [382]:
df['hp_kw'].value_counts()

85.0     2542
66.0     2122
81.0     1402
100.0    1308
110.0    1112
         ...
137.0       1
9.0         1
44.0        1
133.0       1
239.0       1
Name: hp_kw, Length: 80, dtype: int64

In [383]:
df['hp_kw'].value_counts(dropna=False).index.sort_values()

Float64Index([  1.0,   4.0,   9.0,  40.0,  44.0,  51.0,  52.0,  53.0,  54.0,
               55.0,  56.0,  57.0,  60.0,  63.0,  65.0,  66.0,  67.0,  70.0,
               71.0,  74.0,  75.0,  76.0,  77.0,  78.0,  80.0,  81.0,  82.0,
               84.0,  85.0,  86.0,  87.0,  88.0,  89.0,  90.0,  92.0,  93.0,
               96.0,  98.0, 100.0, 101.0, 103.0, 104.0, 110.0, 112.0, 115.0,
              117.0, 118.0, 119.0, 120.0, 121.0, 122.0, 123.0, 125.0, 127.0,
              132.0, 133.0, 135.0, 137.0, 140.0, 141.0, 143.0, 146.0, 147.0,
              149.0, 150.0, 154.0, 155.0, 162.0, 163.0, 164.0, 165.0, 167.0,
              168.0, 184.0, 191.0, 195.0, 228.0, 239.0, 270.0, 294.0,   nan],
             dtype='float64')

In [384]:
df['Type'].head(3)

0    [, Used, , Diesel (Particulate Filter)]
1                       [, Used, , Gasoline]
2    [, Used, , Diesel (Particulate Filter)]
Name: Type, dtype: object

In [385]:
df['Type'].value_counts(dropna=False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[, Used, , Diesel (Particulate Filter)]                                                                                 3475
[, Used, , Diesel]                                                                                                      2516
[, Used, , Gasoline]                                                                                                    2367
[, Used, , Super 95]                                                                                                    1818
[, Pre-registered, , Super 95]                                                                                           500
                                                                                                                        ...
[, New, , Regular/Benzine 91 / Super 95 / Super Plus 98 / Regular/Benzine E10 91 / Super Plus E10 98 / Super E10 95]       1
[, Used, , Super 95 / Super Plus 98 / Super E10 95 / Super Plus E10 98 (Particulate Filter)]                               1
[, Demonstration, , Super Plus 98]                                                                                         1
[, New, , Super Plus E10 98]                                                                                               1
[, Demonstration, , Regular/Benzine E10 91]                                                                                1
Name: Type, Length: 170, dtype: int64

In [386]:
df['Type'].map(lambda x : x[1], na_action='ignore')

0                  Used
1                  Used
2                  Used
3                  Used
4                  Used
              ...
15914               New
15915              Used
15916    Pre-registered
15917    Pre-registered
15918     Demonstration
Name: Type, Length: 15919, dtype: object

In [387]:
df['Type'] = df['Type'].map(lambda x : x[1], na_action='ignore')

In [388]:
df['Type'].value_counts()

Used              11096
New                1650
Pre-registered     1364
Employee's car     1011
Demonstration       796
Name: Type, dtype: int64

In [389]:
df['Fuel'].head(3)

0    [\n, Diesel (Particulate Filter), \n]
1                       [\n, Gasoline, \n]
2    [\n, Diesel (Particulate Filter), \n]
Name: Fuel, dtype: object

In [390]:
df['Fuel'].value_counts(dropna=False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n, Diesel (Particulate Filter), \n]                                                                                  4315
[\n, Super 95, \n]                                                                                                     3338
[\n, Gasoline, \n]                                                                                                     3175
[\n, Diesel, \n]                                                                                                       2984
[\n, Super 95 / Regular/Benzine 91, \n]                                                                                 424
                                                                                                                       ...
[\n, Regular/Benzine 91 / Super 95 / Regular/Benzine E10 91, \n]                                                          1
[\n, Super Plus 98 / Super E10 95, \n]                                                                                    1
[\n, Regular/Benzine 91 / Super 95 / Regular/Benzine E10 91 / Super E10 95 / Super Plus 98 / Super Plus E10 98, \n]       1
[\n, Regular/Benzine 91 / Super Plus 98 / Regular/Benzine E10 91 / Super 95 / Super E10 95 / Super Plus E10 98, \n]       1
[\n, Super Plus 98 / Super 95 / Super Plus E10 98, \n]                                                                    1
Name: Fuel, Length: 77, dtype: int64

In [391]:
df["Fuel"] = df.Fuel.str[1].str.split("/").str[0].str.strip()

In [315]:
#df['Fuel'] = df['Fuel'].map(lambda x : x[1], na_action='ignore')

In [392]:
df['Fuel'].value_counts(dropna=False)

Diesel (Particulate Filter)          4315
Super 95                             4100
Gasoline                             3175
Diesel                               2984
Regular                               503
Super E10 95                          402
Super 95 (Particulate Filter)         268
Gasoline (Particulate Filter)          77
CNG                                    33
LPG                                    16
Super Plus 98                          11
Liquid petroleum gas (LPG)             10
Super E10 95 (Particulate Filter)       7
Electric                                5
Others                                  5
CNG (Particulate Filter)                3
Super Plus E10 98                       2
Others (Particulate Filter)             1
Biogas                                  1
Domestic gas H                          1
Name: Fuel, dtype: int64

In [394]:
df["Fuel"] = df.Fuel.str.split("(").str[0].str.strip()

In [395]:
benzine =['Gasoline', 'Super 95', 'Regular', 'Super E10 95', 'Super Plus 98', 'Super Plus E10 98', 'Others']
lpg = ['LPG', 'Liquid petroleum gas', 'CNG', 'Biogas', 'Domestic gas H']

def fueltype(x):
    if x in benzine:
        return 'Benzine'
    elif x in lpg:
        return 'LPG/CNG'
    else:
        return x
df['Fuel'] = df.Fuel.apply(fueltype)

In [397]:
df['Fuel'].value_counts(dropna=False)

Benzine     8551
Diesel      7299
LPG/CNG       64
Electric       5
Name: Fuel, dtype: int64

In [398]:
df['Inspection_new'].head()

0                 [\nYes\n, \nEuro 6\n]
1                                   NaN
2                                   NaN
3                                   NaN
4    [\nYes\n, \n109 g CO2/km (comb)\n]
Name: Inspection_new, dtype: object

In [399]:
df['Inspection_new'].value_counts(dropna=False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

NaN                                                                                            11987
[\nYes\n, \nEuro 6\n]                                                                            523
\nYes\n                                                                                          362
[\nYes\n, \n102 g CO2/km (comb)\n]                                                               174
[\nYes\n, \n4 (Green)\n]                                                                         166
                                                                                               ...
[\nYes\n, \n, 6 l/100 km (comb), \n, 8 l/100 km (city), \n, 4.9 l/100 km (country), \n]            1
[\nYes\n, \n, 6.8 l/100 km (comb), \n, 8.5 l/100 km (city), \n, 6.1 l/100 km (country), \n]        1
[\nYes\n, \n, 4.1 l/100 km (comb), \n, 7.5 l/100 km (city), \n, 5.2 l/100 km (country), \n]        1
[\nYes\n, \n, 5.2 l/100 km (comb), \n, 6.8 l/100 km (city), \n, 4.3 l/100 km (country), \n]        1
[\nYes\n, \n172 g CO2/km (comb)\n]                                                                 1
Name: Inspection_new, Length: 203, dtype: int64

In [400]:
df['Inspection_new'] = [item[0] if type (item) == list else item for item in df['Inspection_new']]
df['Inspection_new'].head()

0    \nYes\n
1        NaN
2        NaN
3        NaN
4    \nYes\n
Name: Inspection_new, dtype: object

In [401]:
df['Inspection_new'] = df['Inspection_new'].str.strip('\n')

In [402]:
df['Inspection_new'].value_counts(dropna=False)

NaN    11987
Yes     3932
Name: Inspection_new, dtype: int64

In [403]:
df['Warranty'].head()

0             [\n, \n, \n4 (Green)\n]
1                                 NaN
2    [\n, \n, \n99 g CO2/km (comb)\n]
3                                 NaN
4                [\n, \n, \nEuro 6\n]
Name: Warranty, dtype: object

In [404]:
df['Warranty'].value_counts(dropna=False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

NaN                                                                                                5420
[\n, \n, \nEuro 6\n]                                                                               1868
\n12 months\n                                                                                      1177
\n                                                                                                  979
\n24 months\n                                                                                       566
                                                                                                   ...
[\n72 months\n, \n125 g CO2/km (comb)\n]                                                              1
[\n60 months\n, \n14 g CO2/km (comb)\n]                                                               1
[\n24 months\n, \n121 g CO2/km (comb)\n]                                                              1
[\n12 months\n, \nEuro 6d\n]                                                                          1
[\n36 months\n, \n, 7.4 l/100 km (comb), \n, 9.6 l/100 km (city), \n, 6 l/100 km (country), \n]       1
Name: Warranty, Length: 516, dtype: int64

In [405]:
df['Warranty'].isnull().sum()

5420

In [406]:
df['Warranty'] = [item[0] if type (item) == list else item for item in df['Warranty']]
df['Warranty'].head()

0     \n
1    NaN
2     \n
3    NaN
4     \n
Name: Warranty, dtype: object

In [407]:
df['Warranty'] = df['Warranty'].str.strip('\n')
df['Warranty'].head()

0
1    NaN
2
3    NaN
4
Name: Warranty, dtype: object

In [408]:
df['Warranty'].value_counts(dropna=False)

             5646
NaN          5420
12 months    2594
24 months    1118
60 months     401
36 months     279
48 months     149
6 months      125
72 months      59
3 months       33
23 months      11
18 months      10
20 months       7
25 months       6
2 months        5
16 months       4
26 months       4
50 months       4
1 months        3
19 months       3
13 months       3
4 months        3
34 months       3
21 months       2
9 months        2
14 months       2
45 months       2
17 months       2
28 months       2
11 months       2
22 months       2
46 months       2
8 months        1
7 months        1
15 months       1
10 months       1
56 months       1
49 months       1
65 months       1
47 months       1
33 months       1
40 months       1
30 months       1
Name: Warranty, dtype: int64

In [409]:
df['Warranty_month'] = df['Warranty'].str.strip(' months').replace('', np.nan)
df['Warranty_month'].head()

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: Warranty_month, dtype: object

In [410]:
df['Warranty_month'].value_counts(dropna=False)

NaN    11066
12      2594
24      1118
60       401
36       279
48       149
6        125
72        59
3         33
23        11
18        10
20         7
25         6
2          5
50         4
26         4
16         4
4          3
1          3
19         3
34         3
13         3
28         2
22         2
14         2
11         2
46         2
21         2
9          2
17         2
45         2
33         1
40         1
65         1
10         1
15         1
7          1
8          1
56         1
49         1
47         1
30         1
Name: Warranty_month, dtype: int64

In [411]:
df.Body_Color.head()

0    [\n, Black, \n]
1      [\n, Red, \n]
2    [\n, Black, \n]
3    [\n, Brown, \n]
4    [\n, Black, \n]
Name: Body_Color, dtype: object

In [412]:
df.Body_Color.isnull().sum()

597

In [413]:
df['Body_Color'].value_counts(dropna=False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n, Black, \n]     3745
[\n, Grey, \n]      3505
[\n, White, \n]     3406
[\n, Silver, \n]    1647
[\n, Blue, \n]      1431
[\n, Red, \n]        957
NaN                  597
[\n, Brown, \n]      289
[\n, Green, \n]      154
[\n, Beige, \n]      108
[\n, Yellow, \n]      51
[\n, Violet, \n]      18
[\n, Bronze, \n]       6
[\n, Orange, \n]       3
[\n, Gold, \n]         2
Name: Body_Color, dtype: int64

In [414]:
df['Body_Color'] = df['Body_Color'].map(lambda x : (x [1].strip()), na_action='ignore')

df['Body_Color'].value_counts(dropna=False)

Black     3745
Grey      3505
White     3406
Silver    1647
Blue      1431
Red        957
NaN        597
Brown      289
Green      154
Beige      108
Yellow      51
Violet      18
Bronze       6
Orange       3
Gold         2
Name: Body_Color, dtype: int64

In [415]:
df['Nr._of_Doors'] = df['Nr._of_Doors'].map(lambda x : float(x [0].strip('\n')), na_action='ignore')
df['Nr._of_Doors'].head()

0    5.0
1    3.0
2    4.0
3    3.0
4    5.0
Name: Nr._of_Doors, dtype: float64

In [416]:
df['Nr._of_Doors'].value_counts(dropna=False)

5.0    11575
4.0     3079
3.0      832
2.0      219
NaN      212
1.0        1
7.0        1
Name: Nr._of_Doors, dtype: int64

In [417]:
df['Nr._of_Seats'].head()

0    [\n5\n]
1    [\n4\n]
2    [\n4\n]
3    [\n4\n]
4    [\n5\n]
Name: Nr._of_Seats, dtype: object

In [418]:
df['Nr._of_Seats'] = df['Nr._of_Seats'].map(lambda x : float(x [0].strip('\n')), na_action='ignore')
df['Nr._of_Seats'].value_counts(dropna=False)

5.0    13336
4.0     1125
NaN      977
7.0      362
2.0      116
6.0        2
3.0        1
Name: Nr._of_Seats, dtype: int64

In [419]:
df['Gearing_Type'].head()

0    [\n, Automatic, \n]
1    [\n, Automatic, \n]
2    [\n, Automatic, \n]
3    [\n, Automatic, \n]
4    [\n, Automatic, \n]
Name: Gearing_Type, dtype: object

In [420]:
df['Gearing_Type'].value_counts(dropna=False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n, Manual, \n]            8153
[\n, Automatic, \n]         7297
[\n, Semi-automatic, \n]     469
Name: Gearing_Type, dtype: int64

In [421]:
df['Gearing_Type'] = df['Gearing_Type'].map(lambda x : x[1].strip())
df['Gearing_Type'].value_counts(dropna=False)

Manual            8153
Automatic         7297
Semi-automatic     469
Name: Gearing_Type, dtype: int64

In [422]:
df['Displacement_cc'] = df.Displacement.map(lambda x : x[0].strip(' cc\n ').replace(',',''), na_action='ignore').astype('str')

In [423]:
df['Displacement_cc']

0        1422
1        1798
2        1598
3        1422
4        1422
         ...
15914    1997
15915    1798
15916    1997
15917    1997
15918    1798
Name: Displacement_cc, Length: 15919, dtype: object

In [424]:
df[df['Displacement_cc'].isnull()][['Displacement_cc', 'make_model', 'Model_Code']]

Empty DataFrame
Columns: [Displacement_cc, make_model, Model_Code]
Index: []

In [425]:
df.Cylinders.head()

0    [\n3\n]
1    [\n4\n]
2        NaN
3    [\n3\n]
4    [\n3\n]
Name: Cylinders, dtype: object

In [426]:
df['Cylinders'].value_counts(dropna=False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n4\n]    8105
NaN        5680
[\n3\n]    2104
[\n5\n]      22
[\n6\n]       3
[\n8\n]       2
[\n2\n]       2
[\n1\n]       1
Name: Cylinders, dtype: int64

In [427]:
df['Cylinders'] = df['Cylinders'].map(lambda x : float(x [0].strip('\n')), na_action='ignore')
df['Cylinders'].value_counts(dropna=False)

4.0    8105
NaN    5680
3.0    2104
5.0      22
6.0       3
8.0       2
2.0       2
1.0       1
Name: Cylinders, dtype: int64

In [428]:
df['Drive_chain'].head()

0    [\nfront\n]
1    [\nfront\n]
2    [\nfront\n]
3            NaN
4    [\nfront\n]
Name: Drive_chain, dtype: object

In [429]:
df['Drive_chain'] = df['Drive_chain'].map(lambda x : x[0].strip('\n'), na_action='ignore')
df['Drive_chain'].value_counts(dropna=False)

front    8886
NaN      6858
4WD       171
rear        4
Name: Drive_chain, dtype: int64

In [430]:
df.CO2_Emission.head()

0     [\n99 g CO2/km (comb)\n]
1    [\n129 g CO2/km (comb)\n]
2     [\n99 g CO2/km (comb)\n]
3     [\n99 g CO2/km (comb)\n]
4    [\n109 g CO2/km (comb)\n]
Name: CO2_Emission, dtype: object

In [431]:
df['CO2_Emission'].value_counts(dropna=False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

NaN                            1808
[\n120 g CO2/km (comb)\n]       740
[[], [], []]                    628
[\n99 g CO2/km (comb)\n]        545
[\n97 g CO2/km (comb)\n]        537
                               ...
[\n14 g CO2/km (comb)\n]          1
[\n1,060 g CO2/km (comb)\n]       1
[\n51 g CO2/km (comb)\n]          1
[\n165 g CO2/km (comb)\n]         1
[\n193 g CO2/km (comb)\n]         1
Name: CO2_Emission, Length: 124, dtype: int64

In [432]:
df['CO2_Emission'] = [item[0] if type(item) == list else item for item in df['CO2_Emission']]
df['CO2_Emission'] = df['CO2_Emission'].str.strip("\n").str.rstrip(" g CO2/km (comb)").str.replace(",", ".").astype("float")

In [433]:
df['CO2_Emission'].value_counts(dropna=False)

NaN        2436
120.000     740
99.000      545
97.000      537
104.000     501
           ...
990.000       1
12.324        1
1.060         1
51.000        1
193.000       1
Name: CO2_Emission, Length: 121, dtype: int64

In [434]:
df['Emission_Class'].value_counts(dropna=False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\nEuro 6\n]          10139
NaN                    3021
[\nEuro 6d-TEMP\n]     1845
[[], [], []]            607
[\nEuro 6c\n]           127
[\nEuro 5\n]             78
[\nEuro 6d\n]            62
[\nEuro 4\n]             40
Name: Emission_Class, dtype: int64

In [435]:
df['Emission_Class'] = df['Emission_Class'].map(lambda x : np.nan if x[0] == [] else (x[0].strip('\n')), na_action='ignore')

In [436]:
df['Emission_Class'].value_counts(dropna=False)

Euro 6          10139
NaN              3628
Euro 6d-TEMP     1845
Euro 6c           127
Euro 5             78
Euro 6d            62
Euro 4             40
Name: Emission_Class, dtype: int64

In [437]:
df['Comfort_&_Convenience'].head()

0    [Air conditioning, Armrest, Automatic climate ...
1    [Air conditioning, Automatic climate control, ...
2    [Air conditioning, Cruise control, Electrical ...
3    [Air suspension, Armrest, Auxiliary heating, E...
4    [Air conditioning, Armrest, Automatic climate ...
Name: Comfort_&_Convenience, dtype: object

In [438]:
df['Comfort_&_Convenience'].value_counts(dropna=False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          920
[Air conditioning, Electrical side mirrors, Hill Holder, Power windows]                                                                                                                                                                                                                                                                                                                                                                                                                                                      216
[Air conditioning, Electrical side mirrors, Power windows]                                                                                                                                                                                                                                                                                                                                                                                                                                                                   134
[Air conditioning, Power windows]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            130
[Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Leather steering wheel, Light sensor, Lumbar support, Multi-function steering wheel, Navigation system, Park Distance Control, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Start-stop system]                                                                                                                                                         105
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...
[Air conditioning, Cruise control, Electrical side mirrors, Hill Holder, Leather steering wheel, Light sensor, Multi-function steering wheel, Navigation system, Park Distance Control, Parking assist system sensors rear, Power windows, Rain sensor, Split rear seats, Start-stop system, Tinted windows]                                                                                                                                                                                                                   1
[Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Heated steering wheel, Hill Holder, Leather steering wheel, Light sensor, Lumbar support, Multi-function steering wheel, Navigation system, Park Distance Control, Parking assist system camera, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Sunroof]                                                                                                   1
[Air conditioning, Armrest, Cruise control, Electrical side mirrors, Heated steering wheel, Hill Holder, Leather steering wheel, Light sensor, Multi-function steering wheel, Park Distance Control, Parking assist system camera, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Split rear seats, Start-stop system, Tinted windows]                                                                                                                     1
[Air conditioning, Automatic climate control, Cruise control, Electrical side mirrors, Leather steering wheel, Light sensor, Multi-function steering wheel, Park Distance Control, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating]                                                                                                                                                                                                                          1
[Air conditioning, Automatic climate control, Cruise control, Electrically heated windshield, Electrical side mirrors, Electric tailgate, Heads-up display, Heated steering wheel, Hill Holder, Keyless central door lock, Leather steering wheel, Light sensor, Lumbar support, Navigation system, Park Distance Control, Parking assist system camera, Parking assist system self-steering, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Sunroof]      1
Name: Comfort_&_Convenience, Length: 6199, dtype: int64

In [439]:
df['Comfort_&_Convenience'] = [",".join(item) if type(item) == list else item for item in df['Comfort_&_Convenience']]

In [440]:
df['Comfort_&_Convenience'].value_counts(dropna=False)

NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  920
Air conditioning,Electrical side mirrors,Hill Holder,Power windows                                                                                                                                                                                                                                                                                                                                                                                                                                   216
Air conditioning,Electrical side mirrors,Power windows                                                                                                                                                                                                                                                                                                                                                                                                                                               134
Air conditioning,Power windows                                                                                                                                                                                                                                                                                                                                                                                                                                                                       130
Air conditioning,Armrest,Automatic climate control,Cruise control,Electrical side mirrors,Leather steering wheel,Light sensor,Lumbar support,Multi-function steering wheel,Navigation system,Park Distance Control,Parking assist system sensors front,Parking assist system sensors rear,Power windows,Rain sensor,Seat heating,Start-stop system                                                                                                                                                   105
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ...
Air conditioning,Cruise control,Electrical side mirrors,Hill Holder,Leather steering wheel,Light sensor,Multi-function steering wheel,Navigation system,Park Distance Control,Parking assist system sensors rear,Power windows,Rain sensor,Split rear seats,Start-stop system,Tinted windows                                                                                                                                                                                                           1
Air conditioning,Armrest,Automatic climate control,Cruise control,Electrical side mirrors,Heated steering wheel,Hill Holder,Leather steering wheel,Light sensor,Lumbar support,Multi-function steering wheel,Navigation system,Park Distance Control,Parking assist system camera,Parking assist system sensors front,Parking assist system sensors rear,Power windows,Rain sensor,Seat heating,Sunroof                                                                                                1
Air conditioning,Armrest,Cruise control,Electrical side mirrors,Heated steering wheel,Hill Holder,Leather steering wheel,Light sensor,Multi-function steering wheel,Park Distance Control,Parking assist system camera,Parking assist system sensors front,Parking assist system sensors rear,Power windows,Rain sensor,Seat heating,Split rear seats,Start-stop system,Tinted windows                                                                                                                 1
Air conditioning,Automatic climate control,Cruise control,Electrical side mirrors,Leather steering wheel,Light sensor,Multi-function steering wheel,Park Distance Control,Parking assist system sensors front,Parking assist system sensors rear,Power windows,Rain sensor,Seat heating                                                                                                                                                                                                                1
Air conditioning,Automatic climate control,Cruise control,Electrically heated windshield,Electrical side mirrors,Electric tailgate,Heads-up display,Heated steering wheel,Hill Holder,Keyless central door lock,Leather steering wheel,Light sensor,Lumbar support,Navigation system,Park Distance Control,Parking assist system camera,Parking assist system self-steering,Parking assist system sensors front,Parking assist system sensors rear,Power windows,Rain sensor,Seat heating,Sunroof      1
Name: Comfort_&_Convenience, Length: 6199, dtype: int64

In [441]:
df['Entertainment_&_Media'].value_counts(dropna=False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

NaN                                                                                                           1374
[Bluetooth, Hands-free equipment, On-board computer, Radio, USB]                                              1282
[Bluetooth, Hands-free equipment, MP3, On-board computer, Radio, USB]                                          982
[Bluetooth, CD player, Hands-free equipment, MP3, On-board computer, Radio, USB]                               783
[On-board computer, Radio]                                                                                     487
                                                                                                              ...
[Bluetooth, CD player, Digital radio, Hands-free equipment, Radio]                                               1
[CD player, Hands-free equipment, MP3, Radio, USB]                                                               1
[MP3, Radio, Sound system, USB]                                                                                  1
[Bluetooth, MP3, On-board computer, Radio, Television, USB]                                                      1
[Bluetooth, CD player, Hands-free equipment, MP3, On-board computer, Radio, Sound system, Television, USB]       1
Name: Entertainment_&_Media, Length: 347, dtype: int64

In [442]:
df['Entertainment_&_Media'] = [",".join(item) if type(item) == list else item for item in df['Entertainment_&_Media']]

In [443]:
df['Entertainment_&_Media'].value_counts(dropna=False)

NaN                                                                                                 1374
Bluetooth,Hands-free equipment,On-board computer,Radio,USB                                          1282
Bluetooth,Hands-free equipment,MP3,On-board computer,Radio,USB                                       982
Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB                             783
On-board computer,Radio                                                                              487
                                                                                                    ...
Bluetooth,CD player,Digital radio,Hands-free equipment,Radio                                           1
CD player,Hands-free equipment,MP3,Radio,USB                                                           1
MP3,Radio,Sound system,USB                                                                             1
Bluetooth,MP3,On-board computer,Radio,Television,USB                                                   1
Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,Sound system,Television,USB       1
Name: Entertainment_&_Media, Length: 347, dtype: int64

In [444]:
df['Extras'] = [",".join(item) if type(item) == list else item for item in df['Extras']]

In [445]:
df['Extras'].value_counts(dropna=False)

Alloy wheels                                                                                               3245
NaN                                                                                                        2962
Alloy wheels,Touch screen                                                                                   697
Alloy wheels,Voice Control                                                                                  577
Alloy wheels,Touch screen,Voice Control                                                                     541
                                                                                                           ...
Alloy wheels,Catalytic Converter,Shift paddles,Sport package,Sport seats,Sport suspension,Voice Control       1
Alloy wheels,Catalytic Converter,Roof rack,Sport package,Sport seats,Trailer hitch                            1
Alloy wheels,Catalytic Converter,Ski bag,Sport package,Voice Control                                          1
Catalytic Converter,Roof rack,Sport seats,Sport suspension                                                    1
Alloy wheels,Shift paddles,Ski bag,Sport seats,Sport suspension,Touch screen,Voice Control                    1
Name: Extras, Length: 660, dtype: int64

In [446]:
df['Safety_&_Security'] = [",".join(item) if type(item) == list else item for item in df['Safety_&_Security']]

In [447]:
df['Safety_&_Security'].value_counts(dropna=False)

NaN                                                                                                                                                                                                                                                                                                                                                               982
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Fog lights,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                                                                                                                      538
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                                                                                                                                 480
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control,Xenon headlights                                                                                                                                275
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Fog lights,Immobilizer,Isofix,LED Daytime Running Lights,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                                                                                           272
                                                                                                                                                                                                                                                                                                                                                                 ...
ABS,Central door lock,Electronic stability control,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag                                                                                                                                                                                                                                              1
ABS,Adaptive Cruise Control,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Emergency brake assistant,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                                                                                 1
ABS,Adaptive Cruise Control,Alarm system,Central door lock,Driver-side airbag,Electronic stability control,Fog lights,Immobilizer,Isofix,Lane departure warning system,LED Daytime Running Lights,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control,Xenon headlights                                                1
ABS,Adaptive Cruise Control,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Fog lights,Immobilizer,Isofix,Power steering,Tire pressure monitoring system,Traction control                                                                                                                                                  1
ABS,Adaptive Cruise Control,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Emergency brake assistant,Fog lights,Immobilizer,Isofix,Lane departure warning system,LED Daytime Running Lights,LED Headlights,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traffic sign recognition      1
Name: Safety_&_Security, Length: 4444, dtype: int64

In [448]:
df.Gears.head()

0        NaN
1    [\n7\n]
2        NaN
3    [\n6\n]
4        NaN
Name: Gears, dtype: object

In [449]:
df['Gears'].astype(str).value_counts(dropna=False)

['\n6\n']     5822
nan           4712
['\n5\n']     3239
['\n7\n']     1908
['\n8\n']      224
['\n9\n']        6
['\n1\n']        2
['\n3\n']        2
['\n4\n']        2
['\n2\n']        1
['\n50\n']       1
Name: Gears, dtype: int64

In [450]:
df['Gears'] = df['Gears'].map(lambda x : float(x[0].strip('\n')), na_action='ignore')
df['Gears'].value_counts(dropna=False)

6.0     5822
NaN     4712
5.0     3239
7.0     1908
8.0      224
9.0        6
1.0        2
3.0        2
4.0        2
2.0        1
50.0       1
Name: Gears, dtype: int64

In [451]:
all_columns = df.columns.to_list()
all_columns

['url',
 'make_model',
 'short_description',
 'body_type',
 'price',
 'vat',
 'km',
 'registration',
 'prev_owner',
 'kW',
 'hp',
 'Type',
 'Previous_Owners',
 'Next_Inspection',
 'Inspection_new',
 'Warranty',
 'Full_Service',
 'Non-smoking_Vehicle',
 'null',
 'Make',
 'Model',
 'Offer_Number',
 'First_Registration',
 'Body_Color',
 'Paint_Type',
 'Body_Color_Original',
 'Upholstery',
 'Body',
 'Nr._of_Doors',
 'Nr._of_Seats',
 'Model_Code',
 'Gearing_Type',
 'Displacement',
 'Cylinders',
 'Weight',
 'Drive_chain',
 'Fuel',
 'Consumption',
 'CO2_Emission',
 'Emission_Class',
 'Comfort_&_Convenience',
 'Entertainment_&_Media',
 'Extras',
 'Safety_&_Security',
 'description',
 'Emission_Label',
 'Gears',
 'Country_version',
 'Electricity_consumption',
 'Last_Service_Date',
 'Other_Fuel_Types',
 'Availability',
 'Last_Timing_Belt_Service_Date',
 'Available_from',
 'age',
 'hp_kw',
 'Warranty_month',
 'Displacement_cc']

In [452]:
df.drop(["url", "Make", "Model", "null", "short_description", 'Body', 'First_Registration', 'prev_owner', 'kW', 'hp',
         'Warranty', 'Full_Service', 'Next_Inspection', 'Upholstery', 'Model_Code',
         'Non-smoking_Vehicle', 'Offer_Number', 'Displacement', 'Weight', 'Consumption', 'Emission_Label',
         'Country_version', 'Electricity_consumption', 'Last_Service_Date', 'Other_Fuel_Types',
         'Availability', 'Last_Timing_Belt_Service_Date', 'Available_from' ], axis=1, inplace=True)

In [453]:
df.drop(['description', 'Previous_Owners', 'Paint_Type', 'Body_Color_Original'], axis=1, inplace=True)

In [454]:
df.columns

Index(['make_model', 'body_type', 'price', 'vat', 'km', 'registration', 'Type',
       'Inspection_new', 'Body_Color', 'Nr._of_Doors', 'Nr._of_Seats',
       'Gearing_Type', 'Cylinders', 'Drive_chain', 'Fuel', 'CO2_Emission',
       'Emission_Class', 'Comfort_&_Convenience', 'Entertainment_&_Media',
       'Extras', 'Safety_&_Security', 'Gears', 'age', 'hp_kw',
       'Warranty_month', 'Displacement_cc'],
      dtype='object')

In [455]:
df.to_csv('scout_car.csv', index=False)

In [456]:
df.to_csv('scout_car', index=False)

In [457]:
df2 = pd.read_csv('scout_car.csv')

In [458]:
df2.head().T

,0,1,2,3,4
make_model,Audi A1,Audi A1,Audi A1,Audi A1,Audi A1
body_type,Sedans,Sedans,Sedans,Sedans,Sedans
price,15770,14500,14640,14500,16790
vat,VAT deductible,Price negotiable,VAT deductible,NaN,NaN
km,56013.0,80000.0,83450.0,73000.0,16200.0
registration,2016.0,2017.0,2016.0,2016.0,2016.0
Type,Used,Used,Used,Used,Used
Inspection_new,Yes,NaN,NaN,NaN,Yes
Body_Color,Black,Red,Black,Brown,Black
Nr._of_Doors,5.0,3.0,4.0,3.0,5.0
Nr._of_Seats,5.0,4.0,4.0,4.0,5.0
Gearing_Type,Automatic,Automatic,Automatic,Automatic,Automatic
Cylinders,3.0,4.0,NaN,3.0,3.0
Drive_chain,front,front,front,NaN,front
Fuel,Diesel,Benzine,Diesel,Diesel,Diesel
CO2_Emission,99.0,129.0,99.0,99.0,109.0
Emission_Class,Euro 6,Euro 6,Euro 6,Euro 6,Euro 6
Comfort_&_Convenience,"Air conditioning,Armrest,Automatic climate con...","Air conditioning,Automatic climate control,Hil...","Air conditioning,Cruise control,Electrical sid...","Air suspension,Armrest,Auxiliary heating,Elect...","Air conditioning,Armrest,Automatic climate con..."
Entertainment_&_Media,"Bluetooth,Hands-free equipment,On-board comput...","Bluetooth,Hands-free equipment,On-board comput...","MP3,On-board computer","Bluetooth,CD player,Hands-free equipment,MP3,O...","Bluetooth,CD player,Hands-free equipment,MP3,O..."
Extras,"Alloy wheels,Catalytic Converter,Voice Control","Alloy wheels,Sport seats,Sport suspension,Voic...","Alloy wheels,Voice Control","Alloy wheels,Sport seats,Voice Control","Alloy wheels,Sport package,Sport suspension,Vo..."
Safety_&_Security,"ABS,Central door lock,Daytime running lights,D...","ABS,Central door lock,Central door lock with r...","ABS,Central door lock,Daytime running lights,D...","ABS,Alarm system,Central door lock with remote...","ABS,Central door lock,Driver-side airbag,Elect..."
Gears,NaN,7.0,NaN,6.0,NaN
age,3.0,2.0,3.0,3.0,3.0
hp_kw,66.0,141.0,85.0,66.0,66.0
Warranty_month,NaN,NaN,NaN,NaN,NaN
Displacement_cc,1422.0,1798.0,1598.0,1422.0,1422.0

In [507]:
df2["km"].fillna(df["km"].mode()[0], inplace=True)

In [508]:
df2["registration"].fillna(df["registration"].mode()[0], inplace=True)

In [509]:
df2["age"].fillna(df["age"].mode()[0], inplace=True)

In [497]:
df2["Warranty_month"].fillna(df["Warranty_month"].mode()[0], inplace=True)

In [498]:
df2["Gears"].fillna(df["Gears"].mode()[0], inplace=True)

In [500]:
df2["Drive_chain"].fillna(df["Drive_chain"].mode()[0], inplace=True)

In [501]:
df2["Inspection_new"].fillna(df["Inspection_new"].mode()[0], inplace=True)

In [502]:
df2["vat"].fillna(df["vat"].mode()[0], inplace=True)

In [496]:
df2.vat.value_counts(dropna=False)

VAT deductible      15493
Price negotiable      426
Name: vat, dtype: int64

In [459]:
df2.groupby('age').km.describe()

,count,mean,std,min,25%,50%,75%,max
age,,,,,,,,
0.0,2706.0,2085.355137,5365.880693,1.0,10.00,50.0,3000.0,127022.0
1.0,4484.0,18035.239072,11052.524314,1.0,9990.00,17872.0,25078.5,136000.0
2.0,3272.0,41754.940709,28295.747886,1.0,21541.75,34752.0,54805.5,317000.0
3.0,3674.0,77442.520958,39170.142977,10.0,48000.00,72914.5,99950.0,291800.0

In [460]:
df2.groupby(['make_model' ,'age']).km.describe()

                    count          mean           std      min       25%  \
make_model     age
Audi A1        0.0  475.0   2494.501053   3423.569684      1.0     12.00
               1.0  741.0  13785.852901   7978.074930      1.0   7439.00
               2.0  432.0  25821.712963  18608.364225     10.0  14252.50
               3.0  629.0  54332.286169  26281.268811   3150.0  34914.00
Audi A2        1.0    1.0  26166.000000           NaN  26166.0  26166.00
Audi A3        0.0  478.0   2126.757322   7677.530033      1.0     10.00
               1.0  776.0  18410.524485  11054.419659      1.0  11200.00
               2.0  675.0  43853.140741  27349.704178     15.0  25000.00
               3.0  818.0  90092.982885  36464.155900     35.0  62863.25
Opel Astra     0.0  436.0   2915.672018   5539.607697      1.0     10.00
               1.0  721.0  21442.708738  10900.189850      5.0  14000.00
               2.0  587.0  49981.778535  31163.248018     30.0  25201.50
               3.0  519.0  89134.265896  42092.217680  10027.0  57966.00
Opel Corsa     0.0  545.0   1079.616514   3891.048820      1.0     10.00
               1.0  683.0  17426.714495  11747.514046      5.0   8372.50
               2.0  382.0  39977.979058  25985.885203     99.0  20711.25
               3.0  429.0  62904.030303  36449.983186   1800.0  34800.00
Opel Insignia  0.0  300.0   3483.250000   4626.387316      1.0     15.00
               1.0  766.0  22193.801567   8482.243321      1.0  16257.25
               2.0  589.0  47732.103565  32834.327989      1.0  22561.00
               3.0  567.0  93187.985891  41056.814235  10791.0  63000.00
Renault Clio   0.0  258.0    727.282946   6645.562376      1.0     10.00
               1.0  564.0  15396.517730  13314.804279      1.0   5296.25
               2.0  437.0  36660.153318  21098.396486     20.0  23000.00
               3.0  412.0  68564.279126  35608.214970     10.0  42168.25
Renault Duster 0.0   16.0    101.000000      0.000000    101.0    101.00
Renault Espace 0.0  198.0   1755.752525   3768.897756      1.0     10.00
               1.0  232.0  14203.599138  11117.830690      1.0   5187.50
               2.0  170.0  41886.635294  27216.915067      1.0  22313.75
               3.0  300.0  74400.566667  34189.092815   3532.0  49975.00

                        50%        75%       max
make_model     age
Audi A1        0.0    512.0    4000.00   18000.0
               1.0  12411.0   20082.00   47000.0
               2.0  20730.5   32028.75  148257.0
               3.0  50000.0   65500.00  192000.0
Audi A2        1.0  26166.0   26166.00   26166.0
Audi A3        0.0     44.0    1001.00  127022.0
               1.0  18000.0   24215.00  136000.0
               2.0  36677.0   55251.00  158000.0
               3.0  88000.0  112562.50  291800.0
Opel Astra     0.0    984.5    4999.00   88000.0
               1.0  22000.0   28466.00   67500.0
               2.0  44179.0   69188.00  188000.0
               3.0  84900.0  112388.00  260000.0
Opel Corsa     0.0     10.0     100.00   76300.0
               1.0  16600.0   24500.00   70000.0
               2.0  39905.5   54906.75  317000.0
               3.0  55400.0   90000.00  179521.0
Opel Insignia  0.0   1533.0    5138.75   37500.0
               1.0  23931.5   28465.00   70670.0
               2.0  33900.0   77125.00  180033.0
               3.0  88617.0  117500.00  232000.0
Renault Clio   0.0     10.0      99.00  105000.0
               1.0  13685.0   23308.00  113392.0
               2.0  32713.0   46000.00  131494.0
               3.0  63202.0   92032.50  163500.0
Renault Duster 0.0    101.0     101.00     101.0
Renault Espace 0.0     15.0    1510.00   19900.0
               1.0  13587.5   20955.75   62860.0
               2.0  41115.5   49606.00  240000.0
               3.0  68766.0   95000.00  197414.0

In [461]:
df2.groupby(['make_model', 'body_type', 'age']).km.describe()

                                count          mean           std      min  \
make_model     body_type   age
Audi A1        Compact     0.0  129.0   3915.992248   3731.402550      1.0
                           1.0  267.0  14558.460674   8234.372163    973.0
                           2.0  161.0  23698.347826  18465.426052   1478.0
                           3.0  234.0  55367.337607  26688.269985  11300.0
               Coupe       2.0    1.0  50000.000000           NaN  50000.0
...                               ...           ...           ...      ...
Renault Espace Transporter 3.0   37.0  71981.702703  37307.316904   6119.0
               Van         0.0  181.0   1628.928177   3626.858504      1.0
                           1.0  192.0  14226.583333  11387.545450      1.0
                           2.0  134.0  40310.895522  28264.161288      1.0
                           3.0  199.0  74756.979899  34381.250339   3532.0

                                     25%      50%       75%       max
make_model     body_type   age
Audi A1        Compact     0.0   1000.00   3000.0   6000.00   14999.0
                           1.0   7419.50  12900.0  21855.50   33360.0
                           2.0  13938.00  18900.0  27800.00  148257.0
                           3.0  36646.00  49351.0  69373.25  168000.0
               Coupe       2.0  50000.00  50000.0  50000.00   50000.0
...                                  ...      ...       ...       ...
Renault Espace Transporter 3.0  43700.00  82572.0  98000.00  140000.0
               Van         0.0     10.00     15.0   1136.00   19900.0
                           1.0   4450.00  13587.5  20955.75   62860.0
                           2.0  21177.25  38995.0  49606.00  240000.0
                           3.0  48961.00  70000.0  93258.00  197414.0

[151 rows x 8 columns]

In [504]:
df2["Cylinders"].fillna(df["Cylinders"].mode()[0], inplace=True)

In [462]:
df2['body_type'].fillna(df2['body_type'].mode()[0])

0        Sedans
1        Sedans
2        Sedans
3        Sedans
4        Sedans
          ...
15914       Van
15915       Van
15916       Van
15917       Van
15918       Van
Name: body_type, Length: 15919, dtype: object

In [463]:
df2.loc[df2['make_model']=='Audi A1', 'body_type'].fillna(df2[df2['make_model']=='Audi A1']['body_type'].mode()[0])

0        Sedans
1        Sedans
2        Sedans
3        Sedans
4        Sedans
         ...
2609     Sedans
2610     Sedans
2611     Sedans
2612    Compact
2613     Sedans
Name: body_type, Length: 2614, dtype: object

In [464]:
for group in list (df2['make_model'].unique()):
    cond = df2['make_model']==group
    mode = list(df[cond]['body_type'].mode())
    if mode != []:
        df2.loc[cond, 'body_type'] = df2.loc[cond, 'body_type'].fillna(df2[cond]['body_type'].mode()[0])
    else:
        df2.loc[cond, 'body_type'] = df2.loc[cond, 'body_type'].fillna(df2['body_type'].mode()[0])

In [467]:
#df2.["Previous_Owners"].fillna(method="ffill")

SyntaxError: invalid syntax (Temp/ipykernel_1168/1515585881.py, line 1)

In [ ]:
#df2. loc[df["age"]==0, "Previous_Owners"].fillna (method="ffill")

In [ ]:
#for group in list(df2["age"].unique()):

    cond=df["age"]==group

    df.loc[cond, "Previous_Owners"] = df.loc[cond, "Previous_Owners"].fillna(method="ffill").fillna(method="bfill") 
df["Previous Owners"] = df ["Previous_Owners"].fillna (method="ffill").fillna (method="bfill")

In [ ]:
#Step-1

#df.["Paint_Type"].fillna(method="ffill")

In [ ]:
#Step-2

#df.loc[df["make_model"]=="Audi A1", "Paint_Type"].fillna(method="ffill")

In [ ]:
# Step-3

# for group in list(df["make_model"].unique()): 
#     cond=df["make_model"]==group
#     df.loc[cond, "Paint_Type"] = df.loc[cond, "Paint_Type"].fillna(method="ffill").fillna(method="bfill") 
#df["Paint_Type"] = df["Paint_Type"].fillna(method="ffill").fillna(method="bfill")

In [468]:
#Step-4

# for group1 in df["make_model"].unique():

#     for group2 in list (df["body_type"].unique()): 
#         cond2 = (df["make_model"]==group1) & (df["body_type"]==group2) 
#         df.loc[cond2, "Paint_Type"] = df.loc[cond2, "Paint_Type"].fillna (method="ffill").fillna (method="bfill")

# for group in list (df["make_model"].unique()): 
#     condi=df["make_model"]==group1
#     df.loc[cond1, "Paint_Type"] = df.loc[cond1, "Paint_Type"].fillna(method="ffill").fillna(method="bfill")

KeyError: 'Paint_Type'

In [510]:
df2.head().T

,0,1,2,3,4
make_model,Audi A1,Audi A1,Audi A1,Audi A1,Audi A1
body_type,Sedans,Sedans,Sedans,Sedans,Sedans
price,15770,14500,14640,14500,16790
vat,VAT deductible,Price negotiable,VAT deductible,VAT deductible,VAT deductible
km,56013.0,80000.0,83450.0,73000.0,16200.0
registration,2016.0,2017.0,2016.0,2016.0,2016.0
Type,Used,Used,Used,Used,Used
Inspection_new,Yes,Yes,Yes,Yes,Yes
Body_Color,Black,Red,Black,Brown,Black
Nr._of_Doors,5.0,3.0,4.0,3.0,5.0
Nr._of_Seats,5.0,4.0,4.0,4.0,5.0
Gearing_Type,Automatic,Automatic,Automatic,Automatic,Automatic
Cylinders,3.0,4.0,4.0,3.0,3.0
Drive_chain,front,front,front,front,front
Fuel,Diesel,Benzine,Diesel,Diesel,Diesel
CO2_Emission,99.0,129.0,99.0,99.0,109.0
Emission_Class,Euro 6,Euro 6,Euro 6,Euro 6,Euro 6
Comfort_&_Convenience,"Air conditioning,Armrest,Automatic climate con...","Air conditioning,Automatic climate control,Hil...","Air conditioning,Cruise control,Electrical sid...","Air suspension,Armrest,Auxiliary heating,Elect...","Air conditioning,Armrest,Automatic climate con..."
Entertainment_&_Media,"Bluetooth,Hands-free equipment,On-board comput...","Bluetooth,Hands-free equipment,On-board comput...","MP3,On-board computer","Bluetooth,CD player,Hands-free equipment,MP3,O...","Bluetooth,CD player,Hands-free equipment,MP3,O..."
Extras,"Alloy wheels,Catalytic Converter,Voice Control","Alloy wheels,Sport seats,Sport suspension,Voic...","Alloy wheels,Voice Control","Alloy wheels,Sport seats,Voice Control","Alloy wheels,Sport package,Sport suspension,Vo..."
Safety_&_Security,"ABS,Central door lock,Daytime running lights,D...","ABS,Central door lock,Central door lock with r...","ABS,Central door lock,Daytime running lights,D...","ABS,Alarm system,Central door lock with remote...","ABS,Central door lock,Driver-side airbag,Elect..."
Gears,6.0,7.0,6.0,6.0,6.0
age,3.0,2.0,3.0,3.0,3.0
hp_kw,66.0,141.0,85.0,66.0,66.0
Warranty_month,12,12,12,12,12
Displacement_cc,1422.0,1798.0,1598.0,1422.0,1422.0

In [513]:
df2.shape

(15919, 26)

In [511]:
pd.get_dummies(df2)

,price,km,registration,Nr._of_Doors,Nr._of_Seats,Cylinders,CO2_Emission,Gears,age,hp_kw,...,Warranty_month_46.0,Warranty_month_47.0,Warranty_month_48.0,Warranty_month_49.0,Warranty_month_50.0,Warranty_month_56.0,Warranty_month_60.0,Warranty_month_65.0,Warranty_month_72.0,Warranty_month_12
0,15770,56013.0,2016.0,5.0,5.0,3.0,99.0,6.0,3.0,66.0,...,0,0,0,0,0,0,0,0,0,1
1,14500,80000.0,2017.0,3.0,4.0,4.0,129.0,7.0,2.0,141.0,...,0,0,0,0,0,0,0,0,0,1
2,14640,83450.0,2016.0,4.0,4.0,4.0,99.0,6.0,3.0,85.0,...,0,0,0,0,0,0,0,0,0,1
3,14500,73000.0,2016.0,3.0,4.0,3.0,99.0,6.0,3.0,66.0,...,0,0,0,0,0,0,0,0,0,1
4,16790,16200.0,2016.0,5.0,5.0,3.0,109.0,6.0,3.0,66.0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15914,39950,10.0,2018.0,5.0,5.0,4.0,139.0,6.0,1.0,147.0,...,0,0,0,0,0,0,0,0,0,0
15915,39885,9900.0,2019.0,5.0,5.0,4.0,168.0,7.0,0.0,165.0,...,0,0,0,0,0,0,0,0,0,1
15916,39875,15.0,2019.0,5.0,7.0,4.0,139.0,6.0,0.0,146.0,...,0,0,0,0,0,0,0,0,0,1
15917,39700,10.0,2019.0,5.0,7.0,4.0,139.0,6.0,0.0,147.0,...,0,0,0,0,0,0,0,0,0,1
15918,40999,10.0,2019.0,5.0,5.0,4.0,153.0,6.0,0.0,165.0,...,0,0,0,0,0,0,0,0,0,1

In [514]:
df2.to_csv('scout__car.csv', index=False)

In [515]:
df2.to_csv('scout__car', index=False)

In [516]:
df3 = pd.read_csv('scout__car.csv')

In [517]:
df3.head().T

,0,1,2,3,4
make_model,Audi A1,Audi A1,Audi A1,Audi A1,Audi A1
body_type,Sedans,Sedans,Sedans,Sedans,Sedans
price,15770,14500,14640,14500,16790
vat,VAT deductible,Price negotiable,VAT deductible,VAT deductible,VAT deductible
km,56013.0,80000.0,83450.0,73000.0,16200.0
registration,2016.0,2017.0,2016.0,2016.0,2016.0
Type,Used,Used,Used,Used,Used
Inspection_new,Yes,Yes,Yes,Yes,Yes
Body_Color,Black,Red,Black,Brown,Black
Nr._of_Doors,5.0,3.0,4.0,3.0,5.0
Nr._of_Seats,5.0,4.0,4.0,4.0,5.0
Gearing_Type,Automatic,Automatic,Automatic,Automatic,Automatic
Cylinders,3.0,4.0,4.0,3.0,3.0
Drive_chain,front,front,front,front,front
Fuel,Diesel,Benzine,Diesel,Diesel,Diesel
CO2_Emission,99.0,129.0,99.0,99.0,109.0
Emission_Class,Euro 6,Euro 6,Euro 6,Euro 6,Euro 6
Comfort_&_Convenience,"Air conditioning,Armrest,Automatic climate con...","Air conditioning,Automatic climate control,Hil...","Air conditioning,Cruise control,Electrical sid...","Air suspension,Armrest,Auxiliary heating,Elect...","Air conditioning,Armrest,Automatic climate con..."
Entertainment_&_Media,"Bluetooth,Hands-free equipment,On-board comput...","Bluetooth,Hands-free equipment,On-board comput...","MP3,On-board computer","Bluetooth,CD player,Hands-free equipment,MP3,O...","Bluetooth,CD player,Hands-free equipment,MP3,O..."
Extras,"Alloy wheels,Catalytic Converter,Voice Control","Alloy wheels,Sport seats,Sport suspension,Voic...","Alloy wheels,Voice Control","Alloy wheels,Sport seats,Voice Control","Alloy wheels,Sport package,Sport suspension,Vo..."
Safety_&_Security,"ABS,Central door lock,Daytime running lights,D...","ABS,Central door lock,Central door lock with r...","ABS,Central door lock,Daytime running lights,D...","ABS,Alarm system,Central door lock with remote...","ABS,Central door lock,Driver-side airbag,Elect..."
Gears,6.0,7.0,6.0,6.0,6.0
age,3.0,2.0,3.0,3.0,3.0
hp_kw,66.0,141.0,85.0,66.0,66.0
Warranty_month,12.0,12.0,12.0,12.0,12.0
Displacement_cc,1422.0,1798.0,1598.0,1422.0,1422.0